/** تفاصيل برنامج ماجستير إدارة الأعمال (MBA) — للزرع وصفحة الدراسات العليا */

export const mbaDetails = {
  layout: "mba" as const,

  programInfo: {
    titleAr: "MBA - ماجستير في إدارة الأعمال",
    titleEn: "Master of Business Administration",
    affiliationAr: "",
    affiliationEn: "",
    durationAr: "2 سنة دراسية",
    durationEn: "2 academic years",
    totalCreditsAr: "42 ساعة معتمدة",
    totalCreditsEn: "42 credit hours",
    courseCreditsAr: "MBA معتمد",
    courseCreditsEn: "Accredited MBA",
    thesisCreditsAr: "",
    thesisCreditsEn: "",
    quickStat2LabelAr: "الساعات المعتمدة",
    quickStat2LabelEn: "Credit hours",
    quickStat3LabelAr: "نوع الشهادة",
    quickStat3LabelEn: "Degree type",
    quickStat4LabelAr: "",
    quickStat4LabelEn: "",
    aboutLeadAr: "نبذة عن البرنامج",
    aboutLeadEn: "About the program",
    aboutTextAr:
      "برنامج ماجستير إدارة الأعمال (MBA) المتطور الذي يهدف إلى إعداد قادة الأعمال المستقبليين بمهارات إدارية وقيادية متقدمة في مختلف المجالات. يوفر البرنامج معرفة شاملة في الإدارة الاستراتيجية، التمويل، التسويق، العمليات، والموارد البشرية.",
    aboutTextEn:
      "An advanced Master of Business Administration (MBA) program designed to prepare future business leaders with advanced managerial and leadership skills across diverse fields. The program provides comprehensive knowledge in strategic management, finance, marketing, operations, and human resources.",
    studyModeAr: "مسار الرسالة أو مسار الامتحان الشامل",
    studyModeEn: "Thesis track or comprehensive exam track",
    studyModeLabelAr: "مساران للتخرج",
    studyModeLabelEn: "Graduation pathways",
    programDimensionsTextAr:
      "تخصصات شاملة في جميع مجالات الإدارة: الإدارة الاستراتيجية، التمويل، التسويق، العمليات، والموارد البشرية",
    programDimensionsTextEn:
      "Comprehensive coverage across management fields: strategic management, finance, marketing, operations, and human resources",
    programDimensionsLabelAr: "مجالات متنوعة",
    programDimensionsLabelEn: "Diverse domains",
    graduationTitleAr: "",
    graduationTitleEn: "",
    graduationTextAr: "",
    graduationTextEn: "",
    creditsTitleAr: "",
    creditsTitleEn: "",
    creditsTextAr: "",
    creditsTextEn: "",
    creditsBullet1Ar: "",
    creditsBullet2Ar: "",
    creditsBullet1En: "",
    creditsBullet2En: "",
    tracksTitleAr: "",
    tracksTitleEn: "",
    trackPublicAr: "",
    trackPrivateAr: "",
    trackPublicEn: "",
    trackPrivateEn: "",
    objectivesSubtitleAr: "بعد إكمال البرنامج، سيكون الخريج قادراً على:",
    objectivesSubtitleEn: "Upon completing the program, graduates will be able to:",
    outcomesSubtitleAr: "مخرجات التعلم",
    outcomesSubtitleEn: "Learning outcomes",
    studyPlanTitleAr: "متطلبات البرنامج",
    studyPlanTitleEn: "Program requirements",
    section1TitleAr: "أولاً: متطلبات البرنامج الإجبارية (27 ساعة معتمدة)",
    section1TitleEn: "First: mandatory program requirements (27 credit hours)",
    section2TitleAr: "ثانياً: متطلبات البرنامج الاختيارية (9 ساعات معتمدة)",
    section2TitleEn: "Second: elective program requirements (9 credit hours)",
    section2NoteAr:
      "ملاحظة: يختار الطالب 3 مقررات (9 ساعات معتمدة) من المقررات التالية:",
    section2NoteEn: "Note: Students choose three courses (9 credit hours) from the following:",
    section3TitleAr: "ثالثاً: مسارات التخرج — مسار الرسالة (6 ساعات) أو مسار الامتحان الشامل (3 ساعات)",
    section3TitleEn:
      "Third: graduation pathways — thesis track (6 hours) or comprehensive exam track (3 hours)",
    section4TitleAr: "",
    section4TitleEn: "",
  },

  objectives: {
    ar: [
      "تطبيق المبادئ والنظريات الإدارية الحديثة في بيئة الأعمال",
      "تحليل البيانات المالية والإدارية واتخاذ القرارات الاستراتيجية",
      "قيادة الفرق وإدارة الموارد البشرية بفعالية",
      "تطوير الاستراتيجيات التسويقية والتشغيلية للمؤسسات",
      "فهم البيئة الاقتصادية والتجارية العالمية",
      "إجراء البحوث العلمية في مجال إدارة الأعمال",
      "حل المشكلات الإدارية المعقدة باستخدام الأساليب التحليلية",
    ],
    en: [
      "Apply modern management principles and theories in business environments",
      "Analyze financial and managerial data and make strategic decisions",
      "Lead teams and manage human resources effectively",
      "Develop marketing and operational strategies for organizations",
      "Understand the global economic and business environment",
      "Conduct scholarly research in business administration",
      "Solve complex management problems using analytical methods",
    ],
  },

  learningOutcomes: {
    ar: [
      "تطبيق المبادئ والنظريات الإدارية الحديثة في بيئة الأعمال",
      "تحليل البيانات المالية والإدارية واتخاذ القرارات الاستراتيجية",
      "قيادة الفرق وإدارة الموارد البشرية بفعالية",
      "تطوير الاستراتيجيات التسويقية والتشغيلية للمؤسسات",
      "فهم البيئة الاقتصادية والتجارية العالمية",
      "إجراء البحوث العلمية في مجال إدارة الأعمال",
      "حل المشكلات الإدارية المعقدة باستخدام الأساليب التحليلية",
    ],
    en: [
      "Apply modern management principles and theories in business environments",
      "Analyze financial and managerial data and make strategic decisions",
      "Lead teams and manage human resources effectively",
      "Develop marketing and operational strategies for organizations",
      "Understand the global economic and business environment",
      "Conduct scholarly research in business administration",
      "Solve complex management problems using analytical methods",
    ],
  },

  programFeatures: {
    ar: [
      { title: "منظور عالمي", description: "تعلم أفضل الممارسات الإدارية العالمية والمحلية" },
      { title: "مهارات قيادية", description: "تطوير المهارات القيادية والإدارية المتقدمة" },
      { title: "تفكير استراتيجي", description: "القدرة على التخطيط والتفكير الاستراتيجي للأعمال" },
      { title: "اتخاذ القرارات", description: "مهارات تحليلية متقدمة لاتخاذ قرارات مستنيرة" },
      { title: "فرص وظيفية", description: "تأهيل للمناصب الإدارية والقيادية العليا" },
      { title: "الابتكار وريادة الأعمال", description: "تطوير روح الابتكار والقدرة على ريادة الأعمال" },
    ],
    en: [
      { title: "Global perspective", description: "Learn best international and local management practices" },
      { title: "Leadership skills", description: "Develop advanced leadership and management skills" },
      { title: "Strategic thinking", description: "Ability to plan and think strategically for business" },
      { title: "Decision-making", description: "Advanced analytical skills for informed decisions" },
      { title: "Career opportunities", description: "Qualification for senior managerial and leadership roles" },
      { title: "Innovation & entrepreneurship", description: "Foster innovation and entrepreneurial capability" },
    ],
  },

  careerPaths: {
    ar: [
      "مدير تنفيذي (CEO)",
      "مدير عمليات (COO)",
      "مدير مالي (CFO)",
      "مدير تسويق",
      "مدير موارد بشرية",
      "مستشار إدارة أعمال",
      "مدير مشاريع",
      "رائد أعمال",
    ],
    en: [
      "Chief Executive Officer (CEO)",
      "Chief Operating Officer (COO)",
      "Chief Financial Officer (CFO)",
      "Marketing Manager",
      "Human Resources Manager",
      "Business Management Consultant",
      "Project Manager",
      "Entrepreneur",
    ],
  },

  creditSummary: {
    ar: [
      { label: "متطلبات إجبارية", hours: 27 },
      { label: "متطلبات اختيارية", hours: 9 },
      { label: "الرسالة", hours: 6 },
    ],
    en: [
      { label: "Mandatory requirements", hours: 27 },
      { label: "Elective requirements", hours: 9 },
      { label: "Thesis", hours: 6 },
    ],
    totalAr: "42 ساعة معتمدة",
    totalEn: "42 credit hours",
  },

  publicLawCourses: {
    core: [
      { code: "MBA10", titleAr: "الإحصاء التطبيقي في إدارة الأعمال", titleEn: "Applied Statistics in Business Administration", credits: 3 },
      { code: "MBA11", titleAr: "منهجية البحث في إدارة الأعمال", titleEn: "Research Methodology in Business Administration", credits: 3 },
      { code: "MBA12", titleAr: "إدارة التسويق", titleEn: "Marketing Management", credits: 3 },
      { code: "MBA13", titleAr: "إدارة الإنتاج والعمليات", titleEn: "Production and Operations Management", credits: 3 },
      { code: "MBA14", titleAr: "الإدارة المالية", titleEn: "Financial Management", credits: 3 },
      { code: "MBA15", titleAr: "نظرية المنظمة", titleEn: "Organization Theory", credits: 3 },
      { code: "MBA16", titleAr: "الإدارة الاستراتيجية", titleEn: "Strategic Management", credits: 3 },
      { code: "MBA17", titleAr: "إدارة الموارد البشرية", titleEn: "Human Resources Management", credits: 3 },
      { code: "MBA22", titleAr: "المحاسبة الإدارية", titleEn: "Managerial Accounting", credits: 3 },
    ],
    major: [],
    elective: [
      { code: "MBA18", titleAr: "إدارة الأعمال الدولية", titleEn: "International Business Management", credits: 3 },
      { code: "MBA19", titleAr: "إدارة نظم المعلومات", titleEn: "Information Systems Management", credits: 3 },
      { code: "MBA20", titleAr: "مواضيع خاصة في الإدارة", titleEn: "Special Topics in Management", credits: 3 },
      { code: "MBA21", titleAr: "السلوك التنظيمي", titleEn: "Organizational Behavior", credits: 3 },
      { code: "MBA23", titleAr: "إدارة المشاريع", titleEn: "Project Management", credits: 3 },
    ],
    thesis: [
      { code: "MBA30", titleAr: "الرسالة - ماجستير إدارة الأعمال", titleEn: "MBA Thesis", credits: 6 },
    ],
  },

  privateLawCourses: {
    core: [],
    major: [],
    elective: [],
    thesis: [],
  },
};
