import { Award, BookOpen, Database, FileText, Globe, Lightbulb, Search, Sparkles, Target, TrendingUp, Users, Zap } from "lucide-react";

export const aiTools = [
    {
        name: 'Gemini',
        nameAr: 'جيميني',
        provider: 'Google',
        description:
            'هي أداة ذكاء اصطناعي من Google، تهدف إلى تحسين التعامل مع البيانات الضخمة والتعلُّم العميق. وغالباً ما تُستخدم في تطبيقات البحث وتحليل البيانات.',
        descriptionEn: 'AI tool from Google for big data and deep learning',
        url: 'https://gemini.google.com',
        icon: Sparkles,
        headerBg: 'bg-gradient-to-r from-blue-600 to-blue-500',
        borderColor: 'border-blue-200',
        bgColor: 'bg-blue-50',
        textColor: 'text-blue-600',
        btnBg: 'bg-gradient-to-r from-blue-600 to-blue-500',
        features: ['تحليل البيانات الضخمة', 'التعلم العميق', 'البحث الذكي', 'معالجة اللغات الطبيعية'],
        featuresEn: ['Big data analysis', 'Deep learning', 'Smart search', 'Natural language processing'],
    },
    {
        name: 'Elicit',
        nameAr: 'إليسيت',
        provider: 'Elicit.org',
        description:
            'هي أداة قائمة على الذكاء الاصطناعي لتحسين عمليات البحث العلمي. تساعد المستخدمين على صياغة الأسئلة البحثية واستخراج الإجابات المناسبة من الدراسات والمقالات.',
        descriptionEn: 'AI-powered research tool for academic questions',
        url: 'https://elicit.org',
        icon: Search,
        headerBg: 'bg-gradient-to-r from-green-600 to-green-500',
        borderColor: 'border-green-200',
        bgColor: 'bg-green-50',
        textColor: 'text-green-600',
        btnBg: 'bg-gradient-to-r from-green-600 to-green-500',
        features: ['صياغة الأسئلة البحثية', 'استخراج الإجابات من الدراسات', 'تحليل المقالات العلمية', 'تسريع عملية البحث'],
        featuresEn: ['Form research questions', 'Extract answers from papers', 'Analyze academic articles', 'Accelerate research'],
    },
    {
        name: 'AcademicGPT',
        nameAr: 'أكاديميك جي بي تي',
        provider: 'AcademicGPT',
        description:
            'هو نموذج ذكاء اصطناعي مصمم لتقديم إجابات دقيقة للأسئلة الأكاديمية، وغالبًا ما يُستخدم في الأبحاث والمشاريع العلمية.',
        descriptionEn: 'AI model for accurate academic answers',
        url: 'https://academicgpt.net',
        icon: FileText,
        headerBg: 'bg-gradient-to-r from-purple-600 to-purple-500',
        borderColor: 'border-purple-200',
        bgColor: 'bg-purple-50',
        textColor: 'text-purple-600',
        btnBg: 'bg-gradient-to-r from-purple-600 to-purple-500',
        features: ['إجابات أكاديمية دقيقة', 'دعم الأبحاث العلمية', 'المساعدة في المشاريع', 'مراجعة المحتوى الأكاديمي'],
        featuresEn: ['Accurate academic answers', 'Research support', 'Project assistance', 'Academic content review'],
    },
    {
        name: 'Semantic Scholar',
        nameAr: 'سيمانتيك سكولار',
        provider: 'Allen Institute for AI',
        description:
            'محرك بحث أكاديمي مدعوم بالذكاء الاصطناعي يساعد الباحثين على اكتشاف الأوراق العلمية ذات الصلة من خلال فهم السياق والمعنى.',
        descriptionEn: 'AI-powered academic search engine',
        url: 'https://www.semanticscholar.org',
        icon: Database,
        headerBg: 'bg-gradient-to-r from-amber-600 to-amber-500',
        borderColor: 'border-amber-200',
        bgColor: 'bg-amber-50',
        textColor: 'text-amber-600',
        btnBg: 'bg-gradient-to-r from-amber-600 to-amber-500',
        features: ['بحث أكاديمي ذكي', 'فهم السياق والمعنى', 'اكتشاف الأوراق العلمية', 'تحليل الاستشهادات'],
        featuresEn: ['Smart academic search', 'Context-aware understanding', 'Discover relevant papers', 'Citation analysis'],
    },
];

export const benefits = [
    {
        icon: TrendingUp,
        title: 'تحسين الكفاءة',
        titleEn: 'Improved Efficiency',
        description: 'تسريع عمليات البحث والتحليل بشكل كبير',
        descriptionEn: 'Significantly speed up research and analysis',
        bgColor: 'bg-blue-100',
        textColor: 'text-blue-600',
        borderColor: 'border-blue-200',
    },
    {
        icon: Users,
        title: 'تجربة مستخدم محسّنة',
        titleEn: 'Enhanced User Experience',
        description: 'توفير واجهات سهلة وذكية للمستفيدين',
        descriptionEn: 'Provide smart and easy interfaces for users',
        bgColor: 'bg-green-100',
        textColor: 'text-green-600',
        borderColor: 'border-green-200',
    },
    {
        icon: Target,
        title: 'توصيات مخصصة',
        titleEn: 'Personalized Recommendations',
        description: 'اقتراحات مواد بحثية مناسبة لكل مستخدم',
        descriptionEn: 'Recommend relevant academic materials per user',
        bgColor: 'bg-purple-100',
        textColor: 'text-purple-600',
        borderColor: 'border-purple-200',
    },
    {
        icon: Globe,
        title: 'وصول موسع',
        titleEn: 'Expanded Access',
        description: 'ترجمة وتوفير المعلومات لمختلف المستخدمين',
        descriptionEn: 'Translate and broaden access to information',
        bgColor: 'bg-amber-100',
        textColor: 'text-amber-600',
        borderColor: 'border-amber-200',
    },
    {
        icon: Database,
        title: 'إدارة المجموعات',
        titleEn: 'Collection Management',
        description: 'تنظيم وإدارة المصادر الرقمية بكفاءة',
        descriptionEn: 'Organize and manage digital collections efficiently',
        bgColor: 'bg-red-100',
        textColor: 'text-red-600',
        borderColor: 'border-red-200',
    },
    {
        icon: Zap,
        title: 'بحث محسّن',
        titleEn: 'Optimized Search',
        description: 'نتائج بحث أكثر دقة وملاءمة',
        descriptionEn: 'More accurate and relevant search results',
        bgColor: 'bg-teal-100',
        textColor: 'text-teal-600',
        borderColor: 'border-teal-200',
    },
];

export const useCases = [
    {
        title: 'للباحثين',
        titleEn: 'For Researchers',
        icon: Award,
        items: ['البحث في الأوراق العلمية', 'تحليل الأدبيات', 'اكتشاف الاتجاهات البحثية', 'إدارة المراجع'],
        itemsEn: ['Search scientific papers', 'Literature review', 'Discover research trends', 'Manage references'],
        headerBg: 'bg-gradient-to-r from-blue-600 to-blue-500',
        borderColor: 'border-blue-200',
        bgColor: 'bg-blue-50',
        textColor: 'text-blue-600',
    },
    {
        title: 'للطلاب',
        titleEn: 'For Students',
        icon: BookOpen,
        items: ['المساعدة في الواجبات', 'فهم المفاهيم المعقدة', 'إعداد الأبحاث', 'تحسين مهارات الكتابة'],
        itemsEn: ['Assignment help', 'Understand complex concepts', 'Prepare research', 'Improve writing skills'],
        headerBg: 'bg-gradient-to-r from-green-600 to-green-500',
        borderColor: 'border-green-200',
        bgColor: 'bg-green-50',
        textColor: 'text-green-600',
    },
    {
        title: 'لأعضاء هيئة التدريس',
        titleEn: 'For Faculty',
        icon: Lightbulb,
        items: ['تطوير المناهج', 'البحث العلمي', 'إعداد المحاضرات', 'تقييم الطلاب'],
        itemsEn: ['Curriculum development', 'Academic research', 'Lecture preparation', 'Student assessment'],
        headerBg: 'bg-gradient-to-r from-purple-600 to-purple-500',
        borderColor: 'border-purple-200',
        bgColor: 'bg-purple-50',
        textColor: 'text-purple-600',
    },
];
