export const contactsDataArray = [
    { title: 'الدكتور', name: 'محمد فاروق محمد', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '', email: 'mfarouk@buc.edu.om' },
    { title: 'الفاضل', name: 'Vadakkeem Prasanth', department: 'دائرة الشؤون المالية', position: 'Financial Auditor', phone: '+968-25657633', email: 'prasanth@buc.edu.om' },
    { title: 'Miss.', name: 'Marwa Sultan Al Kindi', department: 'دائرة الشؤون المالية', position: 'Financial Auditor', phone: '', email: 'marwa@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد عمر الفرجاني', department: 'قسم إدارة الأعمال والمحاسبة', position: 'رئيس القسم', phone: '+968-25657681', email: 'mfargani@buc.edu.om' },
    { title: 'الدكتور', name: 'ياسر عباس', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مشارك / محاضر', phone: '519', email: 'yasir@buc.edu.om' },
    { title: 'الفاضلة', name: 'مروة عبد القادر', department: 'قسم إدارة الأعمال والمحاسبة', position: 'محاضر', phone: '555', email: 'm.abdelgadir@buc.edu.om' },
    { title: 'Prof.', name: 'ياسر وزيري', department: 'قسم تقنية المعلومات', position: 'دكتور استاذ', phone: '550', email: 'y.wazery@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد عقيل', department: 'قسم تقنية المعلومات', position: 'استاذ مساعد / محاضر', phone: '553', email: 'aqeel@buc.edu.om' },
    { title: 'الدكتور', name: 'عبدالمالك ثابت', department: 'قسم اللغة الأنجليزية وآدابها', position: 'استاذ مشارك / محاضر', phone: '540', email: 'asd.academic@buc.edu.om' },
    { title: 'الفاضل', name: 'عبدالعزيز الكعبي', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '762', email: 'aalkaabi@buc.edu.om' },
    { title: 'الدكتور', name: 'عبدالقادر الدابي', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '423', email: 'abdulkader@buc.edu.om' },
    { title: 'الفاضل', name: 'عبداللة العلوي', department: 'دائرة الشؤون الإدارية', position: 'مدير', phone: '', email: 'aalalawi@buc.edu.om' },
    { title: 'الفاضل', name: 'عبداللة الشامسي', department: 'دائرة الأمن', position: 'موظف أمن', phone: '758', email: 'aalshamsi@buc.edu.om' },
    { title: 'الفاضل', name: 'عبدالرحمن الشامسي', department: 'العمادة', position: 'مكتب الاتصال والعلاقات الخارجية', phone: '+968-25657647', email: 'abdulrahmanah@buc.edu.om' },
    { title: 'الفاضلة', name: 'عبير السديري', department: 'قسم تقنية المعلومات', position: 'محاضر', phone: '567', email: 'abir@buc.edu.om' },
    { title: 'الفاضلة', name: 'عفراء الزيدي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '', email: 'afra@buc.edu.om' },
    { title: 'الدكتور', name: 'أحمد عفيفي', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '516', email: 'aafifi@buc.edu.om' },
    { title: 'الفاضل', name: 'احمد العلوي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'ahmedh@buc.edu.om' },
    { title: 'الفاضل', name: 'احمد الكعبي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'ahmedali@buc.edu.om' },
    { title: 'الفاضل', name: 'احمد الكعبي', department: 'دائرة المكتبة', position: 'موظف مكتبة', phone: '719', email: 'ahmedali@buc.edu.om' },
    { title: 'الفاضل', name: 'أحمد الشامسي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'aralshamsi@buc.edu.om' },
    { title: 'الفاضل', name: 'أحمد الزيدي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'ahmedmas@buc.edu.om' },
    { title: 'الفاضل', name: 'أحمد راشد الكعبي', department: 'دائرة المكتبة', position: 'Acting Director', phone: '716', email: 'ahmedrashid@buc.edu.om' },
    { title: 'Miss.', name: 'العنود المخمري', department: 'دائرة المكتبة', position: 'موظف مكتبة', phone: '717', email: 'alanoud@buc.edu.om' },
    { title: 'الفاضلة', name: 'علياء الغافري', department: 'وحدة المتطلبات العامة', position: 'منسق', phone: '565', email: 'aalghafri@buc.edu.om' },
    { title: 'الفاضل', name: 'علي العبري', department: 'العمادة', position: 'مساعد العميد للشؤون الإدارية والتطوير الوظيفي', phone: '+968-25657699', email: 'asd.admin@buc.edu.om' },
    { title: 'الفاضل', name: 'علي البادي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'aalbadi@buc.edu.om' },
    { title: 'الدكتور', name: 'علي البادي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '427', email: 'alialbadi@buc.edu.om' },
    { title: 'الفاضلة', name: 'علياء الفارسي', department: 'دائرة الشؤون المالية', position: 'موظف إداري', phone: '+968-25657673', email: 'aalfarsi@buc.edu.om' },
    { title: 'الفاضلة', name: 'مريم المنذري', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '745', email: '' },
    { title: 'الدكتور', name: 'أميرة غبدالرحمن', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '408', email: 'amira@buc.edu.om' },
    { title: 'الدكتور', name: 'د. المتولي الشاعر', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '410', email: 'elmetwalli@buc.edu.om' },
    { title: 'الفاضلة', name: 'أمنة الكعبي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'amnaalkaabi@buc.edu.om' },
    { title: 'الفاضل', name: 'أنور الفرقاني', department: 'دائرة الأمن', position: 'مدير', phone: '+968-25657655', email: 'aalfarqani@buc.edu.om' },
    { title: 'Miss.', name: 'أسماء البلوشي', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '585', email: 'aalbulushi@buc.edu.om' },
    { title: 'Miss.', name: 'أسماء الغيثي', department: 'وحدة التدريب', position: 'منسق', phone: '763', email: 'asma@buc.edu.om' },
    { title: 'الفاضلة', name: 'عواطف الحوسني', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '773', email: 'buccounseling@buc.edu.om' },
    { title: 'الدكتور', name: 'أيمن فكري', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '420', email: 'aymanfk@buc.edu.om' },
    { title: 'Miss.', name: 'عائشة العزاني', department: 'البرنامج التأسيسي العام', position: 'منسق', phone: '573', email: 'aalazani@buc.edu.om' },
    { title: 'الفاضلة', name: 'عائشة المعمري', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '761', email: 'aalmaamari@buc.edu.om' },
    { title: 'الفاضل', name: 'عزان المقبالي', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '732', email: 'azzan@buc.edu.om' },
    { title: 'الدكتور', name: 'بابكر صديق', department: 'قسم اللغة الأنجليزية وآدابها', position: 'Assistant Professor / Lecturer / Deputy of Head', phone: '533', email: 'babikir@buc.edu.om' },
    { title: 'الفاضلة', name: 'بدرية الهنائي', department: 'وحدة المتطلبات العامة', position: 'رئيس القسم', phone: '521', email: 'badriya@buc.edu.om' },
    { title: 'الدكتور', name: 'بيداء الدجيلي', department: 'قسم تقنية المعلومات', position: 'استاذ مساعد / محاضر', phone: '552', email: 'baidaa@buc.edu.om' },
    { title: 'الفاضلة', name: 'بسمة البادي', department: 'وحدة التدريب', position: 'مدير', phone: '+968-25657697', email: 'tudirector@buc.edu.om' },
    { title: 'الدكتور', name: 'ضرار المعايطة', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '501', email: 'dirar.almaaitah@buc.edu.om' },
    { title: 'Miss.', name: 'الهام العميري', department: 'Media and Marketing', position: 'مصمم جرافيك', phone: '753', email: 'ealomeiri@buc.edu.om' },
    { title: 'الفاضل', name: 'Elvis', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '591', email: 'elvis@buc.edu.om' },
    { title: 'الدكتور', name: 'فيصل الشقيرات', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '614', email: 'faisal@buc.edu.om' },
    { title: 'الفاضلة', name: 'فاطمة الشامسي', department: 'قسم إدارة الأعمال والمحاسبة', position: 'منسق', phone: '528', email: 'falshamsi@buc.edu.om' },
    { title: 'الفاضلة', name: 'فاطمة اليحيائي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '', email: 'falyahyaai@buc.edu.om' },
    { title: 'الدكتور', name: 'فراس الجميلي', department: 'قسم اللغة الأنجليزية وآدابها', position: 'استاذ مساعد / محاضر', phone: '531', email: 'firas@buc.edu.om' },
    { title: 'الدكتور', name: 'غالية الفارسي', department: 'قسم تقنية المعلومات', position: 'Assistant Professor / Lecturer / Deputy Director', phone: '556', email: 'galfarsi@buc.edu.om' },
    { title: 'الفاضل', name: 'هيثم البلوشي', department: 'دائرة الأمن', position: 'موظف أمن', phone: '', email: 'halbalushi@buc.edu.om' },
    { title: 'الفاضلة', name: 'هاجر العلوي', department: 'وحدة البحث العلمي والابتكار', position: 'حاضنة الأعمال', phone: '507', email: 'hajar@buc.edu.om' },
    { title: 'Miss.', name: 'هاجر العيسائي', department: 'دائرة الشبكات ونظم المعلومات', position: 'مشرف مختبر', phone: '729', email: 'halessai@buc.edu.om' },
    { title: 'الفاضل', name: 'حمد العلوي', department: 'الموارد البشرية', position: 'Employee Sevices Incharge', phone: '736', email: 'halalawi@buc.edu.om' },
    { title: 'الفاضل', name: 'حمد النعيمي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '714', email: 'halnaimi@buc.edu.om' },
    { title: 'Prof.', name: 'حمدي سيد', department: 'برنامج القانون', position: 'دكتور استاذ', phone: '412', email: 'hamdi@buc.edu.om' },
    { title: 'الدكتور', name: 'Mohammed Fathiy Attia', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '', email: 'm.attia@buc.edu.om' },
    { title: 'الفاضل', name: 'هاريش كومار', department: 'دائرة الشؤون المالية', position: 'محاسب', phone: '738', email: 'harish@buc.edu.om' },
    { title: 'الدكتور', name: 'حسان حسن', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '518', email: 'hassan@buc.edu.om' },
    { title: 'Miss.', name: 'هبة الكندي', department: 'دائرة الشؤون المالية', position: 'موظف إداري', phone: '+968-25657686', email: 'hialkindy@buc.edu.om' },
    { title: 'الفاضل', name: 'هلال النعيمي', department: 'دائرة الأمن', position: 'موظف أمن', phone: '', email: 'hilalalnaimi@buc.edu.om' },
    { title: 'الفاضل', name: 'هلال اليزيدي', department: 'دائرة الشؤون الإدارية', position: 'مسؤول النقليات', phone: '740', email: 'hkalzeidi@buc.edu.om' },
    { title: 'الفاضلة', name: 'هند العلوي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '747', email: 'haalalawi@buc.edu.om' },
    { title: 'الفاضلة', name: 'هدى الوحشي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '-', email: 'halwahshi@buc.edu.om' },
    { title: 'الفاضل', name: 'حميد الشامسي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'halshamsi@buc.edu.om' },
    { title: 'الدكتور', name: 'إيجاز خان', department: 'قسم تقنية المعلومات', position: 'استاذ مساعد / محاضر', phone: '551', email: 'ijaz@buc.edu.om' },
    { title: 'Miss.', name: 'إلدا درويش', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '582', email: 'ilda@buc.edu.om' },
    { title: 'الفاضلة', name: 'إيمان العزاني', department: 'العمادة', position: 'مدير مكتب العميد', phone: '+968-25657612', email: 'dean.office@buc.edu.om' },
    { title: 'الفاضل', name: 'عيسى الكعبي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '749', email: 'ialkaabi@buc.edu.om' },
    { title: 'الفاضل', name: 'إسحاق المحمودي', department: 'دائرة الشؤون المالية', position: 'مسؤول مستودعات', phone: '755', email: 'ialmahmoudi@buc.edu.om' },
    { title: 'الفاضل', name: 'إسحاق الصباحي', department: 'دائرة الشؤون المالية', position: 'Casher', phone: '734', email: 'ishaq@buc.edu.om' },
    { title: 'الدكتور', name: 'عيسى الغيثي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '525', email: 'issa@buc.edu.om' },
    { title: 'الدكتور', name: 'جابر العزاني', department: 'دائرة المكتبة', position: 'موظف مكتبة', phone: '568', email: 'jalazzani@buc.edu.om' },
    { title: 'الدكتور', name: 'خالد البادي', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '508', email: 'khaled@buc.edu.om' },
    { title: 'Miss.', name: 'خلود الجابري', department: 'قسم اللغة الأنجليزية وآدابها', position: 'منسق', phone: '548', email: 'kaljabri@buc.edu.om' },
    { title: 'الفاضلة', name: 'خلود العلوي', department: 'الموارد البشرية', position: 'مدير', phone: '+968-25657631', email: 'hr@buc.edu.om' },
    { title: 'الفاضل', name: 'محمود النعيمي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'mahmoodmus@buc.edu.om' },
    { title: 'Prof.', name: 'ممدوح واعر', department: 'برنامج القانون', position: 'رئيس القسم', phone: '+968-25657680', email: 'mamdouh@buc.edu.om' },
    { title: 'الفاضلة', name: 'منال السيابي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '746', email: 'malsiyabi@buc.edu.om' },
    { title: 'الدكتور', name: 'منار المصري', department: 'وحدة المتطلبات العامة', position: 'استاذ مساعد / محاضر', phone: '523', email: 'manar@buc.edu.om' },
    { title: 'Miss.', name: 'مروة الكندي', department: 'دائرة الشؤون المالية', position: 'محاسب', phone: '593', email: 'marwa@buc.edu.om' },
    { title: 'الفاضل', name: 'مروان الهنائي', department: 'Media and Marketing', position: 'تصميم واخراج', phone: '759', email: 'marwan@buc.edu.om' },
    { title: 'Miss.', name: 'مريم العمري', department: 'الموارد البشرية', position: 'موظف إداري', phone: '742', email: 'maryamalamri@buc.edu.om' },
    { title: 'الفاضلة', name: 'مريم المنذري', department: 'دائرة شؤون الطلبة', position: 'مدير', phone: '771', email: 'malmanthari@buc.edu.om' },
    { title: 'الفاضلة', name: 'مريم المقبالي', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '774', email: 'msalmoqbali@buc.edu.om' },
    { title: 'الفاضلة', name: 'مريم النعيمي', department: 'دائرة الشبكات ونظم المعلومات', position: 'Network Engineer', phone: '723', email: 'malnuaimi@buc.edu.om' },
    { title: 'الفاضل', name: 'سعود أحمد', department: 'دائرة الشبكات ونظم المعلومات', position: 'Network Staff', phone: '558', email: 'sawood@buc.edu.om' },
    { title: 'الدكتور', name: 'مريم النعيمي', department: 'قسم اللغة الأنجليزية وآدابها', position: 'استاذ مشارك / محاضر', phone: '503', email: 'maryam@buc.edu.om' },
    { title: 'الفاضلة', name: 'مشاعل العزاني', department: 'Media and Marketing', position: 'Public and Media', phone: '752', email: 'malazani@buc.edu.om' },
    { title: 'الدكتور', name: 'مي المحرزي', department: 'برنامج القانون', position: 'استاذ مشارك / محاضر', phone: '415', email: 'may@buc.edu.om' },
    { title: 'الفاضلة', name: 'ميا العيسائي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '-', email: 'malessaei@buc.edu.om' },
    { title: 'الدكتور', name: 'مايا مانوج', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '+968-25657681', email: 'maya@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد العزيزي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '741', email: 'malazizi@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد طاحون', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '407', email: 'mtahoon@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد البادي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '424', email: 'msalbadi@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد الكعبي', department: 'قسم تقنية المعلومات', position: 'استاذ مساعد / محاضر', phone: '566', email: 'mohammed@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد الكعبي', department: 'قسم تقنية المعلومات', position: 'منسق', phone: '', email: '' },
    { title: 'الفاضل', name: 'محمد الكندي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'malkindi@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد الشامسي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'malshamsi@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد اشفاق', department: 'قسم تقنية المعلومات', position: 'محاضر', phone: '562', email: 'ashfaque@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد العيسوي', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '779', email: 'sportsactivities@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد جهنجير', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مشارك / محاضر', phone: '505', email: 'jahangir@buc.edu.om' },
    { title: 'الفاضل', name: 'محمد مأمون', department: 'وحدة المتطلبات العامة', position: 'محاضر', phone: '522', email: 'mamoon@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد منسي', department: 'قسم اللغة الأنجليزية وآدابها', position: 'استاذ مساعد / محاضر', phone: '434', email: 'mansy@buc.edu.om' },
    { title: 'الفاضل', name: 'موسى الهنائي', department: 'العمادة', position: 'مساعد عميد للخدمات المساندة', phone: '+968-25657634', email: 'asd.support@buc.edu.om' },
    { title: 'الدكتور', name: 'مصطفى لطفي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '401', email: 'mostafalotfy@buc.edu.om' },
    { title: 'الفاضلة', name: 'موزة الشملي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '+968-25657642', email: 'malshumali@buc.edu.om' },
    { title: 'الفاضلة', name: 'موزة اليعقوبي', department: 'دائرة الأمن', position: 'موظف أمن', phone: '', email: 'malyaqoubi@buc.edu.om' },
    { title: 'الفاضل', name: 'مبارك النعيمي', department: 'دائرة شؤون الطلبة', position: 'مساعد رئيس قسم', phone: '777', email: 'mubarak@buc.edu.om' },
    { title: 'الدكتور', name: 'مبارك المقبالي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '418', email: 'malmoqbali@buc.edu.om' },
    { title: 'الدكتور', name: 'محمد أخلاق', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '512', email: 'chohan@buc.edu.om' },
    { title: 'الفاضل', name: 'نبيل عمر حلومي', department: 'Qualility and Assurence', position: 'موظف إداري', phone: '580', email: 'buc_followup@buc.edu.om' },
    { title: 'الفاضل', name: 'نايف الشامسي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'naif@buc.edu.om' },
    { title: 'الفاضلة', name: 'ناجية البلوشي', department: 'دائرة شؤون الطلبة', position: 'ممرضة - العيادة', phone: '+968-25657613', email: 'clinic@buc.edu.om' },
    { title: 'الفاضل', name: 'نفيد خان', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '594', email: 'naveed@buc.edu.om' },
    { title: 'الفاضلة', name: 'نوف المقرشي', department: 'الموارد البشرية', position: 'موظف إداري', phone: '739', email: 'noalmaqrashi@buc.edu.om' },
    { title: 'الفاضلة', name: 'نورة العزاني', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '586', email: 'noura@buc.edu.om' },
    { title: 'الدكتور', name: 'نهى الطيب', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '511', email: 'nuha@buc.edu.om' },
    { title: 'الفاضل', name: 'عمر فريد', department: 'قسم إدارة الأعمال والمحاسبة', position: 'محاضر', phone: '510', email: 'omerfareed@buc.edu.om' },
    { title: 'الفاضلة', name: 'أ. ميمة عبداللة', department: 'قسم إدارة الأعمال والمحاسبة', position: 'محاضر', phone: '502', email: 'omaima@buc.edu.om' },
    { title: 'الفاضل', name: 'باندي راجا رامان', department: 'دائرة الشبكات ونظم المعلومات', position: 'عامل فني', phone: '', email: 'pandiaraja@buc.edu.om' },
    { title: 'الفاضل', name: 'برشانت', department: 'دائرة الشؤون المالية', position: 'مراقب مالي', phone: '+968-25657633', email: 'prasanth@buc.edu.om' },
    { title: 'الدكتور', name: 'رغد توفيق', department: 'قسم تقنية المعلومات', position: 'استاذ مساعد / محاضر', phone: '554', email: 'raghad@buc.edu.om' },
    { title: 'الفاضلة', name: 'رحمة الخليلي', department: 'دائرة القبول والتسجيل', position: 'Head of Scholarshio Affairs', phone: '+968-25657644', email: 'ralkhalili@buc.edu.om' },
    { title: 'Prof.', name: 'رمضان علام', department: 'برنامج القانون', position: 'دكتور استاذ', phone: '421', email: 'rallam@buc.edu.om' },
    { title: 'الدكتور', name: 'رنا النعيمي', department: 'وحدة البحث العلمي والابتكار', position: 'مدير', phone: '+968-25657687', email: 'rana@buc.edu.om' },
    { title: 'الفاضلة', name: 'رشا الساعدي', department: 'برنامج القانون', position: 'منسق', phone: '781', email: 'ralsaadi@buc.edu.om' },
    { title: 'Miss.', name: 'ريما البادي', department: 'Media and Marketing', position: 'مدير', phone: '+968-25657672', email: 'mmdirector@buc.edu.om' },
    { title: 'الدكتور', name: 'روي ماثيو', department: 'قسم تقنية المعلومات', position: 'رئيس القسم', phone: '+968-25657683', email: 'roy@buc.edu.om' },
    { title: 'الفاضلة', name: 'ساديا جابين', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '592', email: 'sadia@buc.edu.om' },
    { title: 'الفاضل', name: 'صغير أحمد', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '597', email: 'saghir@buc.edu.om' },
    { title: 'الفاضل', name: 'سعيد العبري', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'salabri@buc.edu.om' },
    { title: 'الدكتور', name: 'سعيد العلوي', department: 'برنامج القانون', position: 'استاذ مساعد / محاضر', phone: '429', email: 'sjalalawi@buc.edu.om' },
    { title: 'الفاضل', name: 'سعيد الحبسي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'malhabsi@buc.edu.om' },
    { title: 'الفاضل', name: 'سعيد النعيمي', department: 'دائرة القبول والتسجيل', position: 'مدير', phone: '+968-25657640', email: 'salnaaimi@buc.edu.om' },
    { title: 'الفاضل', name: 'سيف العبري', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'saifalabri@buc.edu.om' },
    { title: 'الفاضل', name: 'صلاح عثمان', department: 'قسم اللغة الأنجليزية وآدابها', position: 'محاضر', phone: '535', email: 'salah@buc.edu.om' },
    { title: 'الفاضلة', name: 'سلامة النعيمي', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '589', email: 'salama@buc.edu.om' },
    { title: 'الفاضلة', name: 'سماح الغافري', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '-', email: 'salghafri@buc.edu.om' },
    { title: 'الفاضلة', name: 'سماح المعمري', department: 'وحدة المتطلبات العامة', position: 'محاضر', phone: '526', email: 'samah@buc.edu.om' },
    { title: 'Miss.', name: 'سميرة العريمي', department: 'البرنامج التأسيسي العام', position: 'مساعد رئيس قسم', phone: '584', email: 'samira@buc.edu.om' },
    { title: 'الدكتور', name: 'سامي النعيمي', department: 'قسم اللغة الأنجليزية وآدابها', position: 'استاذ مساعد / محاضر', phone: '544', email: 'sami@buc.edu.om' },
    { title: 'الفاضلة', name: 'سامية منصور', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '776', email: 'smansour@buc.edu.om' },
    { title: 'الفاضل', name: 'شاهر الكعبي', department: 'دائرة شؤون الطلبة', position: 'موظف إداري', phone: '772', email: 'career@buc.edu.om' },
    { title: 'الفاضلة', name: 'شنا البادي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'salbadi@buc.edu.om' },
    { title: 'الفاضلة', name: 'شريفة البطاشي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'salbattashi@buc.edu.om' },
    { title: 'الفاضلة', name: 'شايعة الحاتمي', department: 'دائرة القبول والتسجيل', position: 'موظف إداري', phone: '+968-25657679', email: 'shayah@buc.edu.om' },
    { title: 'الفاضلة', name: 'شيخة العزيزي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '-', email: 'shalazizi@buc.edu.om' },
    { title: 'Miss.', name: 'شيخة الغيثي', department: 'دائرة الشبكات ونظم المعلومات', position: 'Programmer Specialist', phone: '727', email: 'sheikha@buc.edu.om' },
    { title: 'الدكتور', name: 'شيرين الهيتي', department: 'قسم اللغة الأنجليزية وآدابها', position: 'رئيس القسم', phone: '+968-25657682', email: 'sheren@buc.edu.om' },
    { title: 'الدكتور', name: 'سفيان التارقي', department: 'Translation Office', position: 'محاضر', phone: '534', email: 'sofiene@buc.edu.om' },
    { title: 'العمادة', name: 'Assistant Dean for Academic Affairs & Scientific Research', department: '', position: '', phone: '+968-25657683', email: '' },
    { title: 'Miss.', name: 'سمية الكندي', department: 'البرنامج التأسيسي العام', position: 'مدير', phone: '+968-25657684', email: 'salkindi@buc.edu.om' },
    { title: 'Miss.', name: 'سعاد النخيلي', department: 'دائرة الشبكات ونظم المعلومات', position: 'مدير', phone: '724', email: 'salnakhili@buc.edu.om' },
    { title: 'الفاضل', name: 'سلطان البلوشي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'sualbalushi@buc.edu.om' },
    { title: 'الفاضل', name: 'سلطان البلوشي', department: 'دائرة الأمن', position: 'دائرة الأمن', phone: '', email: 'salbalushi@buc.edu.om' },
    { title: 'الفاضل', name: 'سلطان الجهوري', department: 'البرنامج التأسيسي العام', position: 'محاضر', phone: '599', email: 'saljahwari@buc.edu.om' },
    { title: 'الفاضل', name: 'سلطان الكندي', department: 'دائرة الشؤون المالية', position: 'مدير', phone: '+968-25657650', email: 'prm@buc.edu.om' },
    { title: 'الدكتور', name: 'سلطان المزروعي', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '514', email: 'salmazruii@buc.edu.om' },
    { title: 'الفاضل', name: 'سلطان النعيمي', department: 'دائرة الأمن', position: 'موظف أمن', phone: '', email: 'sualnaimi@buc.edu.om' },
    { title: 'الفاضلة', name: 'وضحى الوحشي', department: 'سكن الطالبات', position: 'مشرف سكن', phone: '-', email: 'walwahshi@buc.edu.om' },
    { title: 'الفاضل', name: 'يامن اليحيائي', department: 'دائرة ضمان الجودة', position: 'مدير', phone: '+968-25657690', email: 'qa@buc.edu.om' },
    { title: 'Prof.', name: 'ياسر فؤاد سليم', department: 'العمادة', position: 'عميد كلية البريمي الجامعية', phone: '+968-25657611', email: 'dean@buc.edu.om' },
    { title: 'الدكتور', name: 'زهران اصبحي', department: 'البرنامج التأسيسي العام', position: 'استاذ مساعد / محاضر', phone: '581', email: 'zahran@buc.edu.om' },
    { title: 'الفاضلة', name: 'Zainab Al Araimi', department: 'دائرة الشؤون الإدارية', position: 'Head of Services and Facilities', phone: '+968-25657632', email: 'zalarimi@buc.edu.om' },
    { title: 'الدكتور', name: 'زياد عسولي', department: 'قسم إدارة الأعمال والمحاسبة', position: 'استاذ مساعد / محاضر', phone: '515', email: 'ziad@buc.edu.om' },
    { title: '-', name: 'مجلة اضواء', department: 'مجلة', position: '-', phone: '', email: 'spotlights@buc.edu.om' },
    { title: '-', name: 'الأستقبال', department: 'الموارد البشرية', position: 'الأستقبال', phone: '+968-25657666', email: 'info@buc.edu.om' },
    { title: '-', name: 'نادي البرنامج التأسيسي', department: 'البرنامج التأسيسي العام', position: '-', phone: '', email: 'gfp_club@buc.edu.om' },
    { title: '-', name: 'Hostel Reception Office-1', department: 'سكن الطالبات', position: 'الأستقبال', phone: '783', email: '-' },
    { title: '-', name: 'Hostel Reception Office-2', department: 'سكن الطالبات', position: 'الأستقبال', phone: '784', email: '-' },
    { title: '-', name: 'قسم التوظيف', department: 'الموارد البشرية', position: '-', phone: '-', email: 'recruit@buc.edu.om' },
    { title: '-', name: 'الأمن - البوابة', department: 'دائرة الأمن', position: 'Secuirty Office', phone: '+968-25657638', email: '-' },
    { title: '-', name: 'Security Exit', department: 'دائرة الأمن', position: 'Secuirty Office', phone: '+968-25657637', email: '-' },
    { title: '-', name: 'الأمن مبنى القانون', department: 'دائرة الأمن', position: '-', phone: '757', email: '-' },
    { title: '-', name: 'Security Office', department: 'دائرة الأمن', position: '-', phone: '737', email: '-' },
    { title: '-', name: 'المجلس الاستشاري الطلابي', department: 'دائرة شؤون الطلبة', position: '-', phone: '778', email: 'sc_buc@buc.edu.om' },
    { title: '-', name: 'الخدمات الطلابية', department: 'الخدمات الطلابية', position: '-', phone: '735', email: '-' },
    { title: '-', name: 'الخدمات الطلابية - مبنى القانون', department: 'الخدمات الطلابية', position: '-', phone: '715', email: '-' },
    { title: '-', name: 'مرافق النقل', department: 'دائرة الشؤون الإدارية', position: 'Transpirtation Office', phone: '720', email: '-' },
];