import { Award, BookOpen, Database, Laptop, Lightbulb, Printer, Search, Shield, Users } from "lucide-react";

export const guideFeatures = [
    {
        icon: Search,
        title: 'البحث في الفهرس',
        titleEn: 'Catalog Search',
        description: 'كيفية البحث عن الكتب والمصادر في فهرس المكتبة الإلكتروني',
        descriptionEn: 'How to search for books and resources in the online catalog',
        bgColor: 'bg-blue-100',
        textColor: 'text-blue-600',
        borderColor: 'border-blue-200',
    },
    {
        icon: BookOpen,
        title: 'استعارة الكتب',
        titleEn: 'Book Borrowing',
        description: 'شرح مفصل لإجراءات وسياسات استعارة الكتب والمواد',
        descriptionEn: 'Detailed procedures and policies for borrowing library materials',
        bgColor: 'bg-green-100',
        textColor: 'text-green-600',
        borderColor: 'border-green-200',
    },
    {
        icon: Database,
        title: 'المصادر الإلكترونية',
        titleEn: 'Electronic Resources',
        description: 'الوصول واستخدام قواعد البيانات والمصادر الرقمية',
        descriptionEn: 'Access and use databases and digital resources',
        bgColor: 'bg-purple-100',
        textColor: 'text-purple-600',
        borderColor: 'border-purple-200',
    },
    {
        icon: Users,
        title: 'خدمات المستفيدين',
        titleEn: 'User Services',
        description: 'جميع الخدمات المتاحة للطلبة والباحثين وأعضاء هيئة التدريس',
        descriptionEn: 'Services available for students, researchers, and faculty members',
        bgColor: 'bg-amber-100',
        textColor: 'text-amber-600',
        borderColor: 'border-amber-200',
    },
    {
        icon: Laptop,
        title: 'استعارة الأجهزة',
        titleEn: 'Device Borrowing',
        description: 'سياسات استعارة أجهزة الحاسوب والأجهزة الإلكترونية',
        descriptionEn: 'Policies for borrowing laptops and electronic devices',
        bgColor: 'bg-red-100',
        textColor: 'text-red-600',
        borderColor: 'border-red-200',
    },
    {
        icon: Printer,
        title: 'الطباعة والنسخ',
        titleEn: 'Printing & Copying',
        description: 'استخدام خدمات الطباعة والنسخ والمسح الضوئي',
        descriptionEn: 'Use printing, copying, and scanning services',
        bgColor: 'bg-teal-100',
        textColor: 'text-teal-600',
        borderColor: 'border-teal-200',
    },
];

export const policies = [
    {
        title: 'سياسة الاستعارة',
        titleEn: 'Borrowing Policy',
        icon: BookOpen,
        headerBg: 'bg-gradient-to-r from-blue-600 to-blue-500',
        borderColor: 'border-blue-200',
        bgColor: 'bg-blue-50',
        textColor: 'text-blue-600',
        points: [
            'حدود الاستعارة لكل فئة من المستفيدين',
            'مدة الإعارة وإجراءات التجديد',
            'الغرامات المالية على التأخير',
            'سياسة فقد وإتلاف المواد',
        ],
        pointsEn: ['Borrowing limits per user category', 'Loan duration and renewal procedure', 'Late fines', 'Lost or damaged items policy'],
    },
    {
        title: 'قواعد السلوك',
        titleEn: 'Conduct Rules',
        icon: Shield,
        headerBg: 'bg-gradient-to-r from-green-600 to-green-500',
        borderColor: 'border-green-200',
        bgColor: 'bg-green-50',
        textColor: 'text-green-600',
        points: ['الحفاظ على الهدوء داخل المكتبة', 'احترام المستفيدين الآخرين', 'الحفاظ على نظافة المكتبة', 'الاستخدام السليم للمرافق والمعدات'],
        pointsEn: ['Maintain quietness inside the library', 'Respect other users', 'Keep the library clean', 'Proper use of facilities and equipment'],
    },
    {
        title: 'الوصول والاستخدام',
        titleEn: 'Access & Usage',
        icon: Users,
        headerBg: 'bg-gradient-to-r from-purple-600 to-purple-500',
        borderColor: 'border-purple-200',
        bgColor: 'bg-purple-50',
        textColor: 'text-purple-600',
        points: ['ساعات عمل المكتبة', 'إجراءات دخول المكتبة', 'استخدام البطاقة الجامعية', 'الوصول إلى المصادر الإلكترونية'],
        pointsEn: ['Library working hours', 'Library entry procedures', 'Using the university ID', 'Access to electronic resources'],
    },
    {
        title: 'حقوق الملكية الفكرية',
        titleEn: 'Intellectual Property',
        icon: Award,
        headerBg: 'bg-gradient-to-r from-amber-600 to-amber-500',
        borderColor: 'border-amber-200',
        bgColor: 'bg-amber-50',
        textColor: 'text-amber-600',
        points: ['احترام حقوق النشر والتأليف', 'الاستخدام العادل للمصادر', 'الاقتباس والإشارة للمراجع', 'عدم نسخ المواد بشكل غير قانوني'],
        pointsEn: ['Respect copyright', 'Fair use of resources', 'Proper citation and referencing', 'No illegal copying'],
    },
];

export const procedures = [
    {
        step: '1',
        title: 'التسجيل في المكتبة',
        titleEn: 'Library Registration',
        description: 'احصل على بطاقة المكتبة باستخدام البطاقة الجامعية',
        descriptionEn: 'Use your university ID to register for library services',
        icon: Award,
    },
    {
        step: '2',
        title: 'البحث عن المصادر',
        titleEn: 'Search for Resources',
        description: 'استخدم فهرس المكتبة الإلكتروني للبحث عن الكتب',
        descriptionEn: 'Use the online catalog to find books and resources',
        icon: Search,
    },
    {
        step: '3',
        title: 'استعارة المواد',
        titleEn: 'Borrow Materials',
        description: 'توجه إلى قسم الإعارة مع البطاقة الجامعية',
        descriptionEn: 'Visit the circulation desk with your university ID',
        icon: BookOpen,
    },
    {
        step: '4',
        title: 'الاستفادة من الخدمات',
        titleEn: 'Use Library Services',
        description: 'استخدم المصادر الإلكترونية والخدمات الأخرى',
        descriptionEn: 'Access electronic resources and other services',
        icon: Database,
    },
];

export const quickLinks = [
    {
        title: 'المكتبة الإلكترونية',
        titleEn: 'Library',
        href: '/main/library',
        icon: BookOpen,
        bgColor: 'bg-blue-100',
        textColor: 'text-blue-600',
        borderColor: 'border-blue-200',
    },
    {
        title: 'المصادر الإلكترونية',
        titleEn: 'Electronic Resources',
        href: '/main/library/electronic-resources',
        icon: Database,
        bgColor: 'bg-green-100',
        textColor: 'text-green-600',
        borderColor: 'border-green-200',
    },
    {
        title: 'خدمات المكتبة',
        titleEn: 'Library Services',
        href: '/main/library/library-services',
        icon: Users,
        bgColor: 'bg-purple-100',
        textColor: 'text-purple-600',
        borderColor: 'border-purple-200',
    },
    {
        title: 'أدوات الذكاء الاصطناعي',
        titleEn: 'AI Tools',
        href: '/main/library/ai-tools',
        icon: Lightbulb,
        bgColor: 'bg-amber-100',
        textColor: 'text-amber-600',
        borderColor: 'border-amber-200',
    },
];

export const notesAr = [
    'يجب على جميع المستفيدين إبراز البطاقة الجامعية عند دخول المكتبة',
    'الالتزام بساعات عمل المكتبة والمواعيد المحددة',
    'المحافظة على المواد المعارة وإرجاعها في الموعد المحدد',
    'احترام حقوق الملكية الفكرية عند استخدام المصادر',
    'الالتزام بقواعد السلوك والهدوء داخل المكتبة',
    'عدم تناول الطعام والشراب في قاعات المكتبة',
    'إغلاق الهواتف المحمولة أو وضعها على الوضع الصامت',
];
export const notesEn = [
    'Present your university ID when entering the library',
    'Follow library working hours and schedules',
    'Take care of borrowed materials and return them on time',
    'Respect intellectual property when using resources',
    'Follow conduct rules and keep quiet',
    'No food or drinks inside library halls',
    'Silence your phone or set it to silent mode',
];

export const faqs = [
    {
        qAr: 'كيف يمكنني الحصول على بطاقة المكتبة؟',
        qEn: 'How can I get a library card?',
        aAr: 'يمكنك استخدام بطاقتك الجامعية للوصول إلى جميع خدمات المكتبة.',
        aEn: 'You can use your university ID to access library services.',
    },
    {
        qAr: 'ما هي ساعات عمل المكتبة؟',
        qEn: 'What are the library working hours?',
        aAr: 'المكتبة مفتوحة من الأحد إلى الخميس من الساعة 8:00 صباحاً حتى 8:00 مساءً.',
        aEn: 'The library is open Sunday to Thursday from 8:00 AM to 8:00 PM.',
    },
    {
        qAr: 'كم عدد الكتب التي يمكنني استعارتها؟',
        qEn: 'How many books can I borrow?',
        aAr: 'يعتمد عدد الكتب على فئتك - الطلاب 3 كتب، الدراسات العليا 5 كتب، هيئة التدريس 6 كتب.',
        aEn: 'It depends on your category—students: 3, graduates: 5, faculty: 6.',
    },
    {
        qAr: 'كيف يمكنني الوصول إلى المصادر الإلكترونية؟',
        qEn: 'How do I access electronic resources?',
        aAr: 'يمكنك الوصول إلى جميع المصادر الإلكترونية عبر موقع المكتبة باستخدام اسم المستخدم وكلمة المرور الجامعية.',
        aEn: 'You can access electronic resources via the library website using your university credentials.',
    },
    {
        qAr: 'ماذا يحدث إذا تأخرت في إرجاع كتاب؟',
        qEn: 'What happens if I return a book late?',
        aAr: 'تُفرض غرامة تأخير حسب الفئة - 100 أو 200 بيسة لكل كتاب باليوم حسب الفئة.',
        aEn: 'A late fine applies depending on your category (100–200 Baizas per book/day).',
    },
];
