export const examTypesSeed = [
  {
    nameAr: "الرياضيات",
    nameEn: "Mathematics",
    icon: "Calculator",
    color: "blue",
    order: 1,
    isActive: true,
  },
  {
    nameAr: "الحاسب الآلي",
    nameEn: "Computer",
    icon: "Monitor",
    color: "indigo",
    order: 2,
    isActive: true,
  },
];

export const practiceExamsSeed = [
  {
    code: "GFPM01",
    titleAr: "الرياضيات الأساسية",
    titleEn: "Basic Mathematics",
    subtitleAr: "Basic Mathematics",
    subtitleEn: "Basic Mathematics",
    descriptionAr: "اختبار تجريبي لتقييم المهارات الأساسية في الرياضيات",
    descriptionEn: "Practice exam to assess basic mathematics skills",
    language: "en",
    duration: 50,
    examType: "computerized",
    color: "blue",
    isActive: true,
    order: 1,
  },
  {
    code: "GFPM02",
    titleAr: "الرياضيات البحتة",
    titleEn: "Pure Mathematics",
    subtitleAr: "Pure Mathematics",
    subtitleEn: "Pure Mathematics",
    descriptionAr: "اختبار تجريبي لتقييم الفهم في الرياضيات البحتة",
    descriptionEn: "Practice exam to assess pure mathematics understanding",
    language: "en",
    duration: 50,
    examType: "computerized",
    color: "purple",
    isActive: true,
    order: 2,
  },
  {
    code: "GFPM03",
    titleAr: "الرياضيات التطبيقية",
    titleEn: "Applied Mathematics",
    subtitleAr: "Applied Mathematics",
    subtitleEn: "Applied Mathematics",
    descriptionAr: "اختبار تجريبي لتقييم المهارات في الرياضيات التطبيقية",
    descriptionEn: "Practice exam to assess applied mathematics skills",
    language: "en",
    duration: 50,
    examType: "computerized",
    color: "green",
    isActive: true,
    order: 3,
  },
  {
    code: "GFPM04",
    titleAr: "الرياضيات الأساسية (عربي)",
    titleEn: "Basic Mathematics (Arabic)",
    subtitleAr: "BASIC MATH0",
    subtitleEn: "BASIC MATH0",
    descriptionAr: "اختبار تجريبي باللغة العربية لتقييم المهارات الأساسية في الرياضيات",
    descriptionEn: "Practice exam in Arabic to assess basic mathematics skills",
    language: "ar",
    duration: 50,
    examType: "computerized",
    color: "amber",
    isActive: true,
    order: 4,
  },
  {
    code: "GFPM05",
    titleAr: "الرياضيات التطبيقية (عربي)",
    titleEn: "Applied Mathematics (Arabic)",
    subtitleAr: "Applied Mathematics",
    subtitleEn: "Applied Mathematics",
    descriptionAr: "اختبار تجريبي باللغة العربية لتقييم المهارات في الرياضيات التطبيقية",
    descriptionEn: "Practice exam in Arabic to assess applied mathematics skills",
    language: "ar",
    duration: 50,
    examType: "computerized",
    color: "teal",
    isActive: true,
    order: 5,
  },
  {
    code: "GFPCA1",
    titleAr: "اختبار الحاسب الآلي - المستوى الأول",
    titleEn: "Computer Exam - Level 1",
    subtitleAr: "GFPCA1",
    subtitleEn: "GFPCA1",
    descriptionAr: "اختبار تجريبي لتقييم المهارات الأساسية في الحاسب الآلي",
    descriptionEn: "Practice exam to assess basic computer skills",
    language: "en",
    duration: 50,
    examType: "computerized",
    color: "indigo",
    isActive: true,
    order: 6,
  },
  {
    code: "GFPCA2",
    titleAr: "اختبار الحاسب الآلي - المستوى الثاني",
    titleEn: "Computer Exam - Level 2",
    subtitleAr: "GFPCA2",
    subtitleEn: "GFPCA2",
    descriptionAr: "اختبار تجريبي لتقييم المهارات المتقدمة في الحاسب الآلي",
    descriptionEn: "Practice exam to assess advanced computer skills",
    language: "en",
    duration: 50,
    examType: "computerized",
    color: "red",
    isActive: true,
    order: 7,
  },
];
