export const publicationsSeedData = [
  {
    title: "تقلد المرأة المناصب القيادية في ضوء مقاصد الشرع الكلية",
    type: "book",
    details: "مشاركة في مؤتمر مع النشر رقم الايداع بدار الكتاب المصرية 2019/6176 م",
    author: "أ.بدرية الهنائي",
    year: "2019",
    indexed: false,
    isActive: true,
    order: 1,
  },
  {
    title: "أثر برنامج تدريبي مقترح لتنمية مهارات الكتابة الوظيفية لدى طلبة كلية البريمي الجامعية",
    type: "journal",
    details: "مجلة ايجهار",
    author: "أ.سماح المعمري",
    year: "2021",
    indexed: false,
    isActive: true,
    order: 2,
  },
  {
    title: "القواعد الفقهية المتعلقة بالدور المجتمعي للمؤسسات المالية ورجال الأعمال في مواجهة الأوبئة والجوائح والكوارث والأزمات",
    type: "book",
    details: "مشاركة في مؤتمر مع النشر رقم الايداع بدار الكتاب المصرية 2021/6176 م",
    author: "أ.بدرية الهنائي",
    year: "2021",
    indexed: false,
    isActive: true,
    order: 3,
  },
  {
    title: "Students and Educators Attitudes towards the use of M-Learning: Gender and Smartphone ownership Differences",
    type: "journal",
    details: "International Journal of Interactive Mobile Technologies (iJIM) Vol. (1), pp. 127  135",
    author: "Dr. Yahya Al Khoudary",
    year: "2019",
    indexed: true,
    isActive: true,
    order: 4,
  },
  {
    title: "Difficulties EFL Translation Students Face in Translating Legal Texts into Arabic",
    type: "journal",
    details: "Journal of Scientific Research Ain Shams University No.19, vol.4 ISSN 2356-83-43",
    author: "Amal Alrishan",
    year: "",
    indexed: true,
    isActive: true,
    order: 5,
  },
  {
    title: "Working with Different Text Types in English and Arabic Translation in Practice",
    type: "book",
    details: "Cambridge Scholars Publishing",
    author: "Bahaa-eddin Hassan",
    year: "",
    indexed: true,
    isActive: true,
    order: 6,
  },
  {
    title: "Fear from COVID-19 and technology adoption: the impact of Google Meet during Coronavirus pandemic",
    type: "journal",
    details: "Interactive Learning Environments",
    author: "Dr. Rana Almaroof",
    year: "2020",
    indexed: true,
    isActive: true,
    order: 7,
  },
  {
    title: "Acceptance of Google Meet during the spread of Coronavirus by Arab university students",
    type: "journal",
    details: "Multidisciplinary Digital Publishing Institute",
    author: "Dr. Rana Almaroof",
    year: "2021",
    indexed: true,
    isActive: true,
    order: 8,
  },
  {
    title: "Impact of a new teaching and learning approach in an introductory programming course",
    type: "journal",
    details: "Journal of Educational Computing Research, SAGE",
    author: "Dr. Sohail Iqbal, Jo Coldwell-Neilson",
    year: "2017",
    indexed: true,
    isActive: true,
    order: 9,
  },
  {
    title: "The Impact of Marketing Mix on the Competitive Advantage of the SME sector in the Al Buraimi Governorate in Oman",
    type: "journal",
    details: "SAGE Open, DOI: 10.1177/2158244018800838",
    author: "د. خالد البادي",
    year: "2018",
    indexed: true,
    isActive: true,
    order: 10,
  },
  {
    title: "Testing Growth Theory Using Existing Growth Models for MENA Countries",
    type: "journal",
    details: "International Journal of Economics and Finance; Vol. 12, No. 11",
    author: "Dr. Mohamed Omar Fargani and Dr. Girijasankar Mallik",
    year: "2020",
    indexed: true,
    isActive: true,
    order: 11,
  },
  {
    title: "دراسات في فقه الأحوال الشخصية في الشريعة الإسلامية وفقا لقانون الأحوال الشخصية العماني",
    type: "book",
    details: "نشر دار الكتاب الجامعي",
    author: "أ.د حمدي عبدالله نافع",
    year: "2017",
    indexed: false,
    isActive: true,
    order: 12,
  },
  {
    title: "الحماية القانونية لحائز المعلومات غير المفصح عنها في مجال صناعة الدواء",
    type: "journal",
    details: "مجلة النشر القضائية، المكتب الفني للمحكمة العليا بسلطنة عمان",
    author: "د. مصطفى راتب",
    year: "2020",
    indexed: false,
    isActive: true,
    order: 13,
  },
  {
    title: "العقود الذكية المبرمة على سلسلة الكتل (دراسة مقارنة)",
    type: "journal",
    details: "مجلة الدراسات الفقهية والقانونية  المعهد العالي للقضاء",
    author: "احمد كمال احمد صبري",
    year: "2022",
    indexed: false,
    isActive: true,
    order: 14,
  },
  {
    title: "خصائص الحضارة الإسلامية",
    type: "book",
    details: "مشاركة في مؤتمر مع النشر رقم الايداع بدار الكتاب المصرية 2019/6176 م",
    author: "د.منار المصري",
    year: "2019",
    indexed: false,
    isActive: true,
    order: 15,
  },
];
