export const seminars = [
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Dr. Sohail Malik', title: 'Educational Escape Rooms in Database Course', date: 'Oct-2021' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'د. روي ماثيو', title: 'Creating Personalized Websites For BUC Faculty', date: 'Nov-2021' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Mr. Ijaz Muhammad Khan', title: 'A Systematic Approach to Transform Machine Learning Students\' Performance Prediction Model Into Preventive Procedures', date: 'Dec-2021' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Dr. Baidaa Al Dujaili', title: 'Introduction to Blockchain technology', date: 'Jan-2022' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Mr. Naushad Usmani', title: 'Web application for OOPs problem solving', date: 'Feb-2022' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Mrs. Abir Al Sadairi', title: 'Metaverse: The Next Tech Revolution', date: 'Mar-2022' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Mr. Muhammad Waseem', title: 'RNN: Trends and Challenges', date: 'Apr-2022' },
    { academicYear: '2021 - 2022', department: 'قسم تقنية المعلومات', presenter: 'Dr. Ragad Tawafaq', title: 'Artificial Intelligence Effectiveness and Impact with in COVID 19', date: 'May-2022' },
    { academicYear: '2021 - 2022', department: 'General Requirement Department', presenter: 'أ.سماح المعمري', title: 'ندوة عن اللغة العربية والذكاء الاصطناعي', date: 'Dec-2021' },
    { academicYear: '2021 - 2022', department: 'البرنامج التأسيسي العام', presenter: 'Ms. Asma & Ms. Samira', title: 'How to Create an Effective Online Teacher\'s Portfolio', date: 'Feb-2021' },
    { academicYear: '2021 - 2022', department: 'البرنامج التأسيسي العام', presenter: 'Ms. Maryam Al-Aufi', title: 'Explore and Empower: A Path to Ed Teach Platforms in Teaching', date: 'Dec-2021' },
    { academicYear: '2021 - 2022', department: 'البرنامج التأسيسي العام', presenter: 'Mr. Amr Amer Al Difai', title: 'Fun Learning Strategies for Engaging Students who have been Disengaged', date: 'Jun-2022' },
    { academicYear: '2021 - 2022', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Dr. Amal Alrishan', title: 'Teaching Online Composition Course: Students\' Perspectives', date: 'Oct-2021' },
    { academicYear: '2021 - 2022', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Dr. Firas Aljumaili', title: 'Annie Dillard\'s The Maytrees (2007): A Contemporary Investigation of Transcendental Thought', date: 'Dec-2021' },
    { academicYear: '2021 - 2022', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Dr. Mohamed', title: 'Using Flipped Classroom Model to Improve English Speaking Performance of Omani EFL Learners', date: 'May-2022' },
    { academicYear: '2021 - 2022', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Mr. Sami Al Nuaimi', title: 'New Insights into the African American Identity in Octavia Butler\'s Dawn', date: 'Feb-2022' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'د. محمد الفرجاني', title: 'Class Participation Criteria during online-offline Study', date: 'Nov-2021' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'Dr. Mohammed Jahangir Ali', title: 'The Role of Value Added Tax (VAT) in Business (A General Approach)', date: 'Dec-2021' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'Dr. Mohammed Ikhlaq', title: 'Application of Mathematics in Business and Economics – How to Calculate GPA', date: 'Sep-2021' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'Mr. Syed Talha Hussaini', title: 'Student Advising', date: 'Apr-2022' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'Dr. Mohammed Ikhlaq', title: 'Interpretation of Quranic Verses in Mathematics', date: 'Apr-2022' },
    { academicYear: '2021 - 2022', department: 'Business Administration and Accounting Department', presenter: 'Ms. Hajar Al Alawi', title: 'Why students need to learn Entrepreneur Skills', date: 'Dec-2022' },
    { academicYear: '2022-2023', department: 'قسم تقنية المعلومات', presenter: 'Ms. Abir Al Sadairi', title: 'Horizon Workrooms', date: 'Mar-2023' },
    { academicYear: '2022-2023', department: 'قسم تقنية المعلومات', presenter: 'Mr. Muhammad Waseem', title: 'Introduction of Juice Jacking Technology', date: 'Dec-2022' },
    { academicYear: '2022-2023', department: 'قسم تقنية المعلومات', presenter: 'Dr. Mohammed Al Kaabi', title: 'Mining Social Media', date: 'Jan-2023' },
    { academicYear: '2022-2023', department: 'قسم تقنية المعلومات', presenter: 'Ms. Ghaliya Al Farsi', title: 'Quantum Computing', date: 'Nov-2022' },
    { academicYear: '2022-2023', department: 'قسم تقنية المعلومات', presenter: 'Mr. Ijaz Muhammad Khan', title: 'The Miracles of Artificial Intelligence – An Overview of ChatGPT', date: 'May-2023' },
    { academicYear: '2022-2023', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Mr. Sofien', title: 'Incorporating the use of CSUN 5 Gears in teaching FFL and Translation- Interpreting at BUC', date: 'Nov-2022' },
    { academicYear: '2022-2023', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Dr. Rana Almaroof', title: 'The Effect of Metaverse on Education', date: 'May-2023' },
    { academicYear: '2022-2023', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Mr. Sami Al Nuami', title: 'Syllabus Development Process', date: 'Mar-2023' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'Mr.Mohammed Omer Fareed & Ms.Omaima Abdullah', title: 'Organize the Learning Outcome with the Help of the Oman Qualification Framework (OQF)', date: 'Mar-2023' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'Dr. Khudaija Sultana', title: 'Personal Financial Planning', date: 'Nov-2022' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'Ms. Maya', title: 'Service Quality in Higher Education - (A General Approach on Teaching and Research)', date: 'Mar-2023' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'Ms. Marwa', title: 'Technological Teaching material', date: 'Dec-2022' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'Dr. Mohammed Jahangir Ali', title: 'The Role of Value Added Tax in the Business (A General Approach to develop Business Skills and Pay VAT)', date: 'Jul-2022' },
    { academicYear: '2022-2023', department: 'Business Administration and Accounting Department', presenter: 'د. حسان حسن', title: 'Innovation in Oman An overview', date: 'Dec-2022' },
    { academicYear: '2022-2023', department: 'البرنامج التأسيسي العام', presenter: 'Ms. Hajer Al Essai & Ms. Suad Al Nakhili', title: 'Technical Issues and their Solutions in Classrooms', date: 'Dec-2022' },
    { academicYear: '2022-2023', department: 'البرنامج التأسيسي العام', presenter: 'Ms.Samira Al Araimi', title: 'The Design and Development of Online Service-Learning Communities (OSLC) for General Foundation Program at Al Buraimi University College', date: 'May-2023' },
    { academicYear: '2023 - 2024', department: 'قسم تقنية المعلومات', presenter: 'Dr. Ragad Tawafak', title: 'Mobile Application System Using Augment Reality for Supporting Higher Educational Students', date: 'Jan-2024' },
    { academicYear: '2023 - 2024', department: 'قسم تقنية المعلومات', presenter: 'Dr. Mohammad Al Azawi', title: 'Research Strategies, Ethics and Academic Integrity', date: 'Oct-2023' },
    { academicYear: '2023 - 2024', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'Dr. Abdul-Malik', title: 'Historical Research: Monir Al-Balbaki as a Case Study', date: 'Apr-2024' },
    { academicYear: '2023 - 2024', department: 'قسم اللغة الأنجليزية وآدابها', presenter: 'د. محمد منسي', title: 'Translating Scientific Hints in the Qur\'an', date: 'Mar-2024' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'د. نهى الطيب', title: 'How Artificial Intelligence Benefits Customer Experience', date: 'Mar-2024' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'Dr. Mohammed Ikhlaq', title: 'How to Calculate GPA and Cumulative GPA', date: 'Nov-2023' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'Dr. Dirar Al Maaitah', title: 'How to Prepare Training Program', date: 'Dec-2023' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'د. سلطان المزروعي', title: 'Insights for Managing Human Resources', date: 'Mar-2024' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'د. زياد عسولي', title: 'International Monetary System 1875 till Present', date: 'Nov-2023' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'د. ضرار المعايطة', title: 'Risk Factors in Teaching and Learning During the Academic Years', date: 'May-2024' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'Dr. Faouzi Boujedra', title: 'Sustainable Finance and Environment Impact', date: 'May-2024' },
    { academicYear: '2023 - 2024', department: 'Business Administration and Accounting Department', presenter: 'Dr. Ahmed Al Afifi', title: 'The Role of Financial Literacy for Graduates', date: 'Nov-2023' },
    { academicYear: '2023 - 2024', department: 'البرنامج التأسيسي العام', presenter: 'Ms. Ilda Darwaish', title: 'Improving the Teaching Quality through "Motivation"', date: 'Feb-2024' },
    { academicYear: '2023 - 2024', department: 'البرنامج التأسيسي العام', presenter: 'أ. الفيس بوروز', title: 'Improving the Teaching Quality through "Prior Knowledge"', date: 'Feb-2024' },
    { academicYear: '2023 - 2024', department: 'البرنامج التأسيسي العام', presenter: 'Joaquin, Anna Dina L (CSUN)', title: 'Professional Portfolio Development', date: 'Jan-2024' },
    { academicYear: '2023 - 2024', department: 'البرنامج التأسيسي العام', presenter: 'أ. الفيس بوروز', title: 'The Use of OER Tools to Develop Motivation', date: 'Feb-2023' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د. محمد فتحي عطيه', title: 'الغش بين الشريعة والقانون', date: 'May-2024' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د. محمد ربيع فتح الباب، د.علي بن سالم البادي، د. مي عبد المطلب محرزي', title: 'حلقة نقاشية بعنوان: أخلاقيات ومعايير البحث العلمي', date: 'Dec-2023' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د.علي بن سالم البادي، د.أيمن عبدالله فكري', title: 'حلقة نقاشية بعنوان: المسؤولية القانونية لاستخدام وسائل تقنية المعلومات', date: 'Dec-2023' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د. أيمن عبدالله فكري', title: 'حلقة نقاشية بعنوان: جريمة الاحتيال الإلكتروني', date: 'Dec-2023' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'أ. د. رمضان ابراهيم علام', title: 'حلقة نقاشية بعنوان: دعوى العضل', date: 'Dec-2023' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'الشيخ حمود بن عبدالله بن هلال الحوسني', title: 'دور لجان التوفيق والمصالحة', date: 'May-2024' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د. عمار بن سعيد المانعي', title: 'فضل العشر الأواخر من شهر رمضان المبارك', date: 'Mar-2024' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'د. سعيد بن جمعة العلوي', title: 'كيف نستقبل شهر رمضان', date: 'Mar-2024' },
    { academicYear: '2023 - 2024', department: 'برنامج القانون', presenter: 'أ. د. ياسين ثروت الشاذلي وآخرون', title: 'ندوة قانونية دولية بعنوان: التحكيم التجاري ودوره في تحقيق التنمية المستدامة في ضوء رؤية عمان 2040', date: 'Apr-2024' }
];