export const researchProjectsSeedData = [
  {
    year: "2023-2024",
    investigator: "Entrepreneurial Projects",
    titleAr: "معرض رواد الأعمال",
    titleEn: "Entrepreneurs Exhibition",
    objectives: "يهدف المعرض لدعم المشاريع الصغيرة والمتوسطة واتاحة الفرصة لرواد الأعمال والشركات الطلابية لعرض منتجاتهم وتطويرها.",
    category: "ريادة الأعمال",
    isActive: true,
    order: 1,
  },
  {
    year: "2023-2024",
    investigator: "Entrepreneurial Projects",
    titleAr: "مسابقة فكرة",
    titleEn: "Idea Competition",
    objectives: "سيقوم المتسابقين بتقديم عرض قصير مدته دقيقتين يشرح فيه المتسابق فكرة منتج او خدمة أو مشروع بطريقة تجذب الانتباه، حيث يحاول فيها الريادي اقناع المستثمر بأن فكرته تستحق الاستثمار.",
    category: "ريادة الأعمال",
    isActive: true,
    order: 2,
  },
  {
    year: "2023-2024",
    investigator: "Ms. Abeer with a group of students",
    titleEn: "Injaz Oman",
    objectives: "تسعى \"انجاز عمان\" لدعم الاقتصاد العماني عن طريق توفير فرص عمل للمجتمعات وتعزيز الأعمال الصغيرة والمتوسطة، كما تحفز الابتكار والابداع في تقديم الخدمات السياحية والبرامج الثقافية.",
    category: "ريادة الأعمال",
    isActive: true,
    order: 3,
  },
  {
    year: "2023-2024",
    investigator: "Ms. Abeer Al Zahraa Al Sinani, Al Anoud Al Azzizi",
    titleEn: "Upgrade Competition",
    objectives: "It aims at transforming ideas into business projects",
    category: "ريادة الأعمال",
    isActive: true,
    order: 4,
  },
  {
    year: "2023-2024",
    investigator: "Ms. Hajar Al Alawi, Dr. Hasan Hassan",
    titleEn: "Innovation Index Forum",
    objectives: "The aim of the Innovation Index Forum is to enhance understanding and promote the importance of innovation in driving economic growth and development. This forum brings together policymakers, industry leaders, academics, and innovators to discuss best practices, share insights, and explore strategies for fostering a culture of innovation.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 5,
  },
  {
    year: "2023-2024",
    investigator: "Dr. Ragad M Tawafak, Mr. AbdulQader AL Shibli",
    titleEn: "Innovation Festival in Muscat / Online participation",
    objectives: "The aim of the Innovation Festival in Muscat is to promote a culture of innovation and creativity across various sectors in Oman. The festival serves as a platform to showcase innovative ideas, technologies, and solutions that can address local and global challenges.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 6,
  },
  {
    year: "2023-2024",
    investigator: "Abdullah Al Farsi, Sultan Al Yaarubi",
    titleEn: "Innovation Festival in Muscat",
    objectives: "The aim of the Innovation Festival in Muscat is to promote a culture of innovation and creativity across various sectors in Oman. The festival serves as a platform to showcase innovative ideas, technologies, and solutions that can address local and global challenges.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 7,
  },
  {
    year: "2023-2024",
    investigator: "Ms. Ghaliya Al Farsi, Abdullah Al Farsi, Sultan Al Yarubi",
    titleEn: "Innovation Festival in SQU",
    objectives: "The festival serves as a platform to showcase innovative projects, research, and entrepreneurial ideas that address real-world challenges.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 8,
  },
  {
    year: "2023-2024",
    investigator: "Dr. Rana Alnaimi, Ms. Maryam Alazani",
    titleEn: "One to One Innovation Competition in Malaysia",
    objectives: "The One-to-One Innovation Competition in Malaysia aims to foster creativity and entrepreneurship among participants by encouraging innovative solutions to real world challenges. It focuses on identifying and developing unique ideas that can lead to new products, services, or processes.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 9,
  },
  {
    year: "2023-2024",
    investigator: "Dr. Ragad M Tawafak, Ms. Ghaliya Alfarsi, Ms. Abir Alsideiri, Mr. Saif AlShamsi",
    titleEn: "One-to-One Innovation Competition in UTAS/Ibri",
    objectives: "The One-to-One Innovation Competition at the University of Technology and Applied Sciences (UTAS) in Ibri aims to promote a culture of innovation and entrepreneurship among students. The competition provides a platform for participants to present their creative ideas and projects.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 10,
  },
  {
    year: "2023-2024",
    investigator: "Al Yaziya Al Jabri",
    titleEn: "Falling Wall Competition KSA",
    objectives: "The Falling Walls Competition aims to celebrate and promote innovative research and ideas that have the potential to address significant global challenges. The competition encourages participants to present their groundbreaking projects and solutions in a compelling format.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 11,
  },
  {
    year: "2023-2024",
    investigator: "Al Yaziya Al Jabri, Abdullah Al Farsi",
    titleEn: "Falling Wall Competition Muscat",
    objectives: "The Falling Walls Competition in Muscat aims to celebrate and promote innovative research and ideas that have the potential to address significant global challenges.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 12,
  },
  {
    year: "2023-2024",
    investigator: "Ms. Abir Alsideiri, Sultan Saif Alyarubi, Aisha Suleiman Alsaidi, Dana Mohammed Alnaimi, Salha Khalid Albaloshi, Omar Hamood Al Shukaili",
    titleEn: "NASA Hackathon",
    objectives: "The aim is to encourage innovation and creativity in solving challenges related to space exploration and Earth sciences. This global event brings together participants from various backgrounds—including developers, designers, scientists, and enthusiasts—to collaborate and develop projects.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 13,
  },
  {
    year: "2023-2024",
    investigator: "Abdullah Al Farsi, Sultan Al Yarubi, Ammar Al Yahyaei, Nhyian Al Bulushi, Alyazia Al Jabri, Sheikha Al Balushi",
    titleEn: "In-pipe Inspection Robot (IIR) Student's Competition",
    objectives: "The In-pipe Inspection Robot (IIR) Student Competition specifically aims to encourage engineering students to innovate and design robots capable of inspecting pipelines.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 14,
  },
  {
    year: "2023-2024",
    investigator: "Abdullah Al Farsi, Sultan Al Yarubi, Ammar Al Yahyaei, Nhyian Al Bulushi, Alyazia Al Jabri, Sheikha Al Balushi, Abdullah Al Balushi",
    titleEn: "Buraimi Hackathon",
    objectives: "The event brings together students, professionals, and enthusiasts to collaborate, share ideas, and create impactful projects within a limited timeframe. It emphasizes teamwork, problem-solving, and the application of technology to enhance community development.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 15,
  },
  {
    year: "2023-2024",
    investigator: "Mr. Taimur Al Busaidi",
    titleEn: "Buraimi Hackathon organized by the Governor's Office Al Buraimi",
    objectives: "The event brings together students, professionals, and enthusiasts to collaborate, share ideas, and create impactful projects within a limited timeframe.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 16,
  },
  {
    year: "2021-2022",
    investigator: "Ghaliya Al Farsi",
    titleEn: "Facilitation for Al Buraimi College Undergraduate to learn Java Language Using E Learning Model",
    objectives: "The objectives of this application make the problem easy to solve to memorization and understanding of programming codes in the programming languages of Java. Save time and avoid problems that may students face when programming.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 17,
  },
  {
    year: "2021-2022",
    investigator: "د. بيداء حمزة",
    titleEn: "An Optimizing Rebroadcast Mechanism for Minimizing the Control Overhead in Mobile Ad-hoc Networks",
    objectives: "The objective of this research project is to improve network performance by proposing an optimized route discovery mechanism for minimizing the control overhead in on demand source routing protocols.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 18,
  },
  {
    year: "2022-2023",
    investigator: "Dr. Baidaa Hamza Khudayer, Dr. Ragad Tawafak & Dr. Sohail Iqbal",
    titleEn: "A Comparative Performance Evaluation of Routing Protocols for Mobile Ad-hoc Networks",
    objectives: "The objective of this research project is to conduct a comparative analysis of the three groups of MANET routing protocols by comparing their features and methods.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 19,
  },
  {
    year: "2022-2023",
    investigator: "د. بيداء حمزة",
    titleEn: "Probabilistic Detection of Indoor Events Using A Wireless Sensor Network-Based",
    objectives: "The objective of the project titled \"Probabilistic Detection of Indoor Events Using a Wireless Sensor Network-Based Mechanism\" is to develop an innovative approach for detecting events in indoor environments.",
    category: "تقنية المعلومات",
    isActive: true,
    order: 20,
  },
  {
    year: "2024-2025",
    investigator: "سفيان التارقي",
    titleEn: "Exploring Translation Students' Performance in Converting Arabic Idioms and Proverbs to English: Insights and Recommendations",
    objectives: "The aim is to evaluate and analyze the challenges faced by translation students when converting Arabic idioms and proverbs into English.",
    category: "تعليمي",
    isActive: true,
    order: 21,
  },
  {
    year: "2022-2023",
    investigator: "Abir Al Sideiri, Dr. Raghad Tawafaq & Ghaliya Al Farsi",
    titleEn: "Impact of Software Engineering Problem Based Learning on Students' Academic Performance",
    objectives: "The objective of this research is to adapt Software Engineering Problem Based Learning (SEPBL) approach and compare this approach with the traditional approach.",
    category: "تعليمي",
    isActive: true,
    order: 22,
  },
  {
    year: "2022-2023",
    investigator: "Ghaliya AL Farsi",
    titleEn: "The efficiency of the UTAUT2 model in predicting student acceptance of the virtual reality learning system",
    objectives: "This study aims to determine the extent to which students accept the Moodle virtual reality learning system at the Universities and the direct effects of the UTAUT2 model variables on the intention behavior.",
    category: "تعليمي",
    isActive: true,
    order: 23,
  },
  {
    year: "2023-2024",
    investigator: "Dr. Ahmed Al Afeefi",
    titleEn: "Green Finance - The National Science Week",
    objectives: "The objective is to raise awareness about the importance of green finance in promoting sustainable economic growth and addressing environmental challenges.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 24,
  },
  {
    year: "2023-2024",
    investigator: "Mr. Mohammed Al-Nuaimi, Mr. Asaad Al Sharji, Mr. Abdullah Alfarsi",
    titleEn: "The National Science Week Exhibition",
    objectives: "The National Science Week Exhibition aims to promote awareness and appreciation of science among the public. It seeks to inspire curiosity, encourage engagement with scientific concepts, and highlight the importance of science and technology in everyday life.",
    category: "الابتكار والتنافسية",
    isActive: true,
    order: 25,
  },
  {
    year: "2022-2023",
    investigator: "رمضان إبراهيم عبد الكريم موسى",
    titleAr: "تيسير إجراءات التقاضي في خصوص قانون الإجراءات المدنية العماني",
    titleEn: "Facilitating litigation procedures regarding the Omani Civil Procedures Law",
    objectives: "تهدف هذه الدراسة الى تحليل وتيسير إجراءات التقاضي في إطار قانون الإجراءات المدنية العماني، من خلال تقييم فعالية القوانين والأنظمة الحالية، تحديد التحديات التي تواجه المتقاضيين والمحاميين.",
    category: "قانوني",
    isActive: true,
    order: 26,
  },
];
