export const seminarsSeed = [
  // 2021-2022 Academic Year - Information Technology Department
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Sohail Malik",
    presenterEn: "Dr. Sohail Malik",
    titleAr: "Educational Escape Rooms in Database Course",
    titleEn: "Educational Escape Rooms in Database Course",
    date: "2021-10-01",
    isActive: true,
    order: 1,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "د. روي ماثيو",
    presenterEn: "Dr. Roy Matthew",
    titleAr: "Creating Personalized Websites For BUC Faculty",
    titleEn: "Creating Personalized Websites For BUC Faculty",
    date: "2021-11-01",
    isActive: true,
    order: 2,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mr. Ijaz Muhammad Khan",
    presenterEn: "Mr. Ijaz Muhammad Khan",
    titleAr: "A Systematic Approach to Transform Machine Learning Students' Performance Prediction Model Into Preventive Procedures",
    titleEn: "A Systematic Approach to Transform Machine Learning Students' Performance Prediction Model Into Preventive Procedures",
    date: "2021-12-01",
    isActive: true,
    order: 3,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Baidaa Al Dujaili",
    presenterEn: "Dr. Baidaa Al Dujaili",
    titleAr: "Introduction to Blockchain technology",
    titleEn: "Introduction to Blockchain technology",
    date: "2022-01-01",
    isActive: true,
    order: 4,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mr. Naushad Usmani",
    presenterEn: "Mr. Naushad Usmani",
    titleAr: "Web application for OOPs problem solving",
    titleEn: "Web application for OOPs problem solving",
    date: "2022-02-01",
    isActive: true,
    order: 5,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mrs. Abir Al Sadairi",
    presenterEn: "Mrs. Abir Al Sadairi",
    titleAr: "Metaverse: The Next Tech Revolution",
    titleEn: "Metaverse: The Next Tech Revolution",
    date: "2022-03-01",
    isActive: true,
    order: 6,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mr. Muhammad Waseem",
    presenterEn: "Mr. Muhammad Waseem",
    titleAr: "RNN: Trends and Challenges",
    titleEn: "RNN: Trends and Challenges",
    date: "2022-04-01",
    isActive: true,
    order: 7,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Ragad Tawafaq",
    presenterEn: "Dr. Ragad Tawafaq",
    titleAr: "Artificial Intelligence Effectiveness and Impact with in COVID 19",
    titleEn: "Artificial Intelligence Effectiveness and Impact with in COVID 19",
    date: "2022-05-01",
    isActive: true,
    order: 8,
  },
  // 2021-2022 Academic Year - General Requirement Department
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم المتطلبات العامة",
    departmentEn: "General Requirement Department",
    presenterAr: "أ.سماح المعمري",
    presenterEn: "Prof. Samah Al Mamari",
    titleAr: "ندوة عن اللغة العربية والذكاء الاصطناعي",
    titleEn: "Seminar on Arabic Language and Artificial Intelligence",
    date: "2021-12-01",
    isActive: true,
    order: 9,
  },
  // 2021-2022 Academic Year - Foundation Program
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Ms. Asma & Ms. Samira",
    presenterEn: "Ms. Asma & Ms. Samira",
    titleAr: "How to Create an Effective Online Teacher's Portfolio",
    titleEn: "How to Create an Effective Online Teacher's Portfolio",
    date: "2021-02-01",
    isActive: true,
    order: 10,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Ms. Maryam Al-Aufi",
    presenterEn: "Ms. Maryam Al-Aufi",
    titleAr: "Explore and Empower: A Path to Ed Teach Platforms in Teaching",
    titleEn: "Explore and Empower: A Path to Ed Teach Platforms in Teaching",
    date: "2021-12-01",
    isActive: true,
    order: 11,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Mr. Amr Amer Al Difai",
    presenterEn: "Mr. Amr Amer Al Difai",
    titleAr: "Fun Learning Strategies for Engaging Students who have been Disengaged",
    titleEn: "Fun Learning Strategies for Engaging Students who have been Disengaged",
    date: "2022-06-01",
    isActive: true,
    order: 12,
  },
  // 2021-2022 Academic Year - English Department
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Dr. Amal Alrishan",
    presenterEn: "Dr. Amal Alrishan",
    titleAr: "Teaching Online Composition Course: Students' Perspectives",
    titleEn: "Teaching Online Composition Course: Students' Perspectives",
    date: "2021-10-01",
    isActive: true,
    order: 13,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Dr. Firas Aljumaili",
    presenterEn: "Dr. Firas Aljumaili",
    titleAr: "Annie Dillard's The Maytrees (2007): A Contemporary Investigation of Transcendental Thought",
    titleEn: "Annie Dillard's The Maytrees (2007): A Contemporary Investigation of Transcendental Thought",
    date: "2021-12-01",
    isActive: true,
    order: 14,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Dr. Mohamed",
    presenterEn: "Dr. Mohamed",
    titleAr: "Using Flipped Classroom Model to Improve English Speaking Performance of Omani EFL Learners",
    titleEn: "Using Flipped Classroom Model to Improve English Speaking Performance of Omani EFL Learners",
    date: "2022-05-01",
    isActive: true,
    order: 15,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Mr. Sami Al Nuaimi",
    presenterEn: "Mr. Sami Al Nuaimi",
    titleAr: "New Insights into the African American Identity in Octavia Butler's Dawn",
    titleEn: "New Insights into the African American Identity in Octavia Butler's Dawn",
    date: "2022-02-01",
    isActive: true,
    order: 16,
  },
  // 2021-2022 Academic Year - Business Administration
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. محمد الفرجاني",
    presenterEn: "Dr. Mohamed Al Farjani",
    titleAr: "Class Participation Criteria during online-offline Study",
    titleEn: "Class Participation Criteria during online-offline Study",
    date: "2021-11-01",
    isActive: true,
    order: 17,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Mohammed Jahangir Ali",
    presenterEn: "Dr. Mohammed Jahangir Ali",
    titleAr: "The Role of Value Added Tax (VAT) in Business (A General Approach)",
    titleEn: "The Role of Value Added Tax (VAT) in Business (A General Approach)",
    date: "2021-12-01",
    isActive: true,
    order: 18,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Mohammed Ikhlaq",
    presenterEn: "Dr. Mohammed Ikhlaq",
    titleAr: "Application of Mathematics in Business and Economics – How to Calculate GPA",
    titleEn: "Application of Mathematics in Business and Economics – How to Calculate GPA",
    date: "2021-09-01",
    isActive: true,
    order: 19,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Mr. Syed Talha Hussaini",
    presenterEn: "Mr. Syed Talha Hussaini",
    titleAr: "Student Advising",
    titleEn: "Student Advising",
    date: "2022-04-01",
    isActive: true,
    order: 20,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Mohammed Ikhlaq",
    presenterEn: "Dr. Mohammed Ikhlaq",
    titleAr: "Interpretation of Quranic Verses in Mathematics",
    titleEn: "Interpretation of Quranic Verses in Mathematics",
    date: "2022-04-01",
    isActive: true,
    order: 21,
  },
  {
    academicYearAr: "2021 - 2022",
    academicYearEn: "2021 - 2022",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Ms. Hajar Al Alawi",
    presenterEn: "Ms. Hajar Al Alawi",
    titleAr: "Why students need to learn Entrepreneur Skills",
    titleEn: "Why students need to learn Entrepreneur Skills",
    date: "2022-12-01",
    isActive: true,
    order: 22,
  },
  // 2022-2023 Academic Year - Information Technology
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Ms. Abir Al Sadairi",
    presenterEn: "Ms. Abir Al Sadairi",
    titleAr: "Horizon Workrooms",
    titleEn: "Horizon Workrooms",
    date: "2023-03-01",
    isActive: true,
    order: 23,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mr. Muhammad Waseem",
    presenterEn: "Mr. Muhammad Waseem",
    titleAr: "Introduction of Juice Jacking Technology",
    titleEn: "Introduction of Juice Jacking Technology",
    date: "2022-12-01",
    isActive: true,
    order: 24,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Mohammed Al Kaabi",
    presenterEn: "Dr. Mohammed Al Kaabi",
    titleAr: "Mining Social Media",
    titleEn: "Mining Social Media",
    date: "2023-01-01",
    isActive: true,
    order: 25,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Ms. Ghaliya Al Farsi",
    presenterEn: "Ms. Ghaliya Al Farsi",
    titleAr: "Quantum Computing",
    titleEn: "Quantum Computing",
    date: "2022-11-01",
    isActive: true,
    order: 26,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Mr. Ijaz Muhammad Khan",
    presenterEn: "Mr. Ijaz Muhammad Khan",
    titleAr: "The Miracles of Artificial Intelligence – An Overview of ChatGPT",
    titleEn: "The Miracles of Artificial Intelligence – An Overview of ChatGPT",
    date: "2023-05-01",
    isActive: true,
    order: 27,
  },
  // 2022-2023 Academic Year - English Department
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Mr. Sofien",
    presenterEn: "Mr. Sofien",
    titleAr: "Incorporating the use of CSUN 5 Gears in teaching FFL and Translation- Interpreting at BUC",
    titleEn: "Incorporating the use of CSUN 5 Gears in teaching FFL and Translation- Interpreting at BUC",
    date: "2022-11-01",
    isActive: true,
    order: 28,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Dr. Rana Almaroof",
    presenterEn: "Dr. Rana Almaroof",
    titleAr: "The Effect of Metaverse on Education",
    titleEn: "The Effect of Metaverse on Education",
    date: "2023-05-01",
    isActive: true,
    order: 29,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Mr. Sami Al Nuami",
    presenterEn: "Mr. Sami Al Nuami",
    titleAr: "Syllabus Development Process",
    titleEn: "Syllabus Development Process",
    date: "2023-03-01",
    isActive: true,
    order: 30,
  },
  // 2022-2023 Academic Year - Business Administration
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Mr.Mohammed Omer Fareed & Ms.Omaima Abdullah",
    presenterEn: "Mr.Mohammed Omer Fareed & Ms.Omaima Abdullah",
    titleAr: "Organize the Learning Outcome with the Help of the Oman Qualification Framework (OQF)",
    titleEn: "Organize the Learning Outcome with the Help of the Oman Qualification Framework (OQF)",
    date: "2023-03-01",
    isActive: true,
    order: 31,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Khudaija Sultana",
    presenterEn: "Dr. Khudaija Sultana",
    titleAr: "Personal Financial Planning",
    titleEn: "Personal Financial Planning",
    date: "2022-11-01",
    isActive: true,
    order: 32,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Ms. Maya",
    presenterEn: "Ms. Maya",
    titleAr: "Service Quality in Higher Education - (A General Approach on Teaching and Research)",
    titleEn: "Service Quality in Higher Education - (A General Approach on Teaching and Research)",
    date: "2023-03-01",
    isActive: true,
    order: 33,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Ms. Marwa",
    presenterEn: "Ms. Marwa",
    titleAr: "Technological Teaching material",
    titleEn: "Technological Teaching material",
    date: "2022-12-01",
    isActive: true,
    order: 34,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Mohammed Jahangir Ali",
    presenterEn: "Dr. Mohammed Jahangir Ali",
    titleAr: "The Role of Value Added Tax in the Business (A General Approach to develop Business Skills and Pay VAT)",
    titleEn: "The Role of Value Added Tax in the Business (A General Approach to develop Business Skills and Pay VAT)",
    date: "2022-07-01",
    isActive: true,
    order: 35,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. حسان حسن",
    presenterEn: "Dr. Hassan Hassan",
    titleAr: "Innovation in Oman An overview",
    titleEn: "Innovation in Oman An overview",
    date: "2022-12-01",
    isActive: true,
    order: 36,
  },
  // 2022-2023 Academic Year - Foundation Program
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Ms. Hajer Al Essai & Ms. Suad Al Nakhili",
    presenterEn: "Ms. Hajer Al Essai & Ms. Suad Al Nakhili",
    titleAr: "Technical Issues and their Solutions in Classrooms",
    titleEn: "Technical Issues and their Solutions in Classrooms",
    date: "2022-12-01",
    isActive: true,
    order: 37,
  },
  {
    academicYearAr: "2022-2023",
    academicYearEn: "2022-2023",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Ms.Samira Al Araimi",
    presenterEn: "Ms.Samira Al Araimi",
    titleAr: "The Design and Development of Online Service-Learning Communities (OSLC) for General Foundation Program at Al Buraimi University College",
    titleEn: "The Design and Development of Online Service-Learning Communities (OSLC) for General Foundation Program at Al Buraimi University College",
    date: "2023-05-01",
    isActive: true,
    order: 38,
  },
  // 2023-2024 Academic Year - Information Technology
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Ragad Tawafak",
    presenterEn: "Dr. Ragad Tawafak",
    titleAr: "Mobile Application System Using Augment Reality for Supporting Higher Educational Students",
    titleEn: "Mobile Application System Using Augment Reality for Supporting Higher Educational Students",
    date: "2024-01-01",
    isActive: true,
    order: 39,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم تقنية المعلومات",
    departmentEn: "Information Technology Department",
    presenterAr: "Dr. Mohammad Al Azawi",
    presenterEn: "Dr. Mohammad Al Azawi",
    titleAr: "Research Strategies, Ethics and Academic Integrity",
    titleEn: "Research Strategies, Ethics and Academic Integrity",
    date: "2023-10-01",
    isActive: true,
    order: 40,
  },
  // 2023-2024 Academic Year - English Department
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "Dr. Abdul-Malik",
    presenterEn: "Dr. Abdul-Malik",
    titleAr: "Historical Research: Monir Al-Balbaki as a Case Study",
    titleEn: "Historical Research: Monir Al-Balbaki as a Case Study",
    date: "2024-04-01",
    isActive: true,
    order: 41,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم اللغة الأنجليزية وآدابها",
    departmentEn: "English Language and Literature Department",
    presenterAr: "د. محمد منسي",
    presenterEn: "Dr. Mohamed Mansi",
    titleAr: "Translating Scientific Hints in the Qur'an",
    titleEn: "Translating Scientific Hints in the Qur'an",
    date: "2024-03-01",
    isActive: true,
    order: 42,
  },
  // 2023-2024 Academic Year - Business Administration
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. نهى الطيب",
    presenterEn: "Dr. Noha Al Tayeb",
    titleAr: "How Artificial Intelligence Benefits Customer Experience",
    titleEn: "How Artificial Intelligence Benefits Customer Experience",
    date: "2024-03-01",
    isActive: true,
    order: 43,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Mohammed Ikhlaq",
    presenterEn: "Dr. Mohammed Ikhlaq",
    titleAr: "How to Calculate GPA and Cumulative GPA",
    titleEn: "How to Calculate GPA and Cumulative GPA",
    date: "2023-11-01",
    isActive: true,
    order: 44,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Dirar Al Maaitah",
    presenterEn: "Dr. Dirar Al Maaitah",
    titleAr: "How to Prepare Training Program",
    titleEn: "How to Prepare Training Program",
    date: "2023-12-01",
    isActive: true,
    order: 45,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. سلطان المزروعي",
    presenterEn: "Dr. Sultan Al Mazroui",
    titleAr: "Insights for Managing Human Resources",
    titleEn: "Insights for Managing Human Resources",
    date: "2024-03-01",
    isActive: true,
    order: 46,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. زياد عسولي",
    presenterEn: "Dr. Ziad Asouli",
    titleAr: "International Monetary System 1875 till Present",
    titleEn: "International Monetary System 1875 till Present",
    date: "2023-11-01",
    isActive: true,
    order: 47,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "د. ضرار المعايطة",
    presenterEn: "Dr. Dirar Al Maaitah",
    titleAr: "Risk Factors in Teaching and Learning During the Academic Years",
    titleEn: "Risk Factors in Teaching and Learning During the Academic Years",
    date: "2024-05-01",
    isActive: true,
    order: 48,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Faouzi Boujedra",
    presenterEn: "Dr. Faouzi Boujedra",
    titleAr: "Sustainable Finance and Environment Impact",
    titleEn: "Sustainable Finance and Environment Impact",
    date: "2024-05-01",
    isActive: true,
    order: 49,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "قسم إدارة الأعمال والمحاسبة",
    departmentEn: "Business Administration and Accounting Department",
    presenterAr: "Dr. Ahmed Al Afifi",
    presenterEn: "Dr. Ahmed Al Afifi",
    titleAr: "The Role of Financial Literacy for Graduates",
    titleEn: "The Role of Financial Literacy for Graduates",
    date: "2023-11-01",
    isActive: true,
    order: 50,
  },
  // 2023-2024 Academic Year - Foundation Program
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Ms. Ilda Darwaish",
    presenterEn: "Ms. Ilda Darwaish",
    titleAr: "Improving the Teaching Quality through \"Motivation\"",
    titleEn: "Improving the Teaching Quality through \"Motivation\"",
    date: "2024-02-01",
    isActive: true,
    order: 51,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "أ. الفيس بوروز",
    presenterEn: "Prof. Elvis Borroz",
    titleAr: "Improving the Teaching Quality through \"Prior Knowledge\"",
    titleEn: "Improving the Teaching Quality through \"Prior Knowledge\"",
    date: "2024-02-01",
    isActive: true,
    order: 52,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "Joaquin, Anna Dina L (CSUN)",
    presenterEn: "Joaquin, Anna Dina L (CSUN)",
    titleAr: "Professional Portfolio Development",
    titleEn: "Professional Portfolio Development",
    date: "2024-01-01",
    isActive: true,
    order: 53,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "البرنامج التأسيسي العام",
    departmentEn: "Foundation Program",
    presenterAr: "أ. الفيس بوروز",
    presenterEn: "Prof. Elvis Borroz",
    titleAr: "The Use of OER Tools to Develop Motivation",
    titleEn: "The Use of OER Tools to Develop Motivation",
    date: "2023-02-01",
    isActive: true,
    order: 54,
  },
  // 2023-2024 Academic Year - Law Program
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د. محمد فتحي عطيه",
    presenterEn: "Dr. Mohamed Fathi Atia",
    titleAr: "الغش بين الشريعة والقانون",
    titleEn: "Cheating between Sharia and Law",
    date: "2024-05-01",
    isActive: true,
    order: 55,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د. محمد ربيع فتح الباب، د.علي بن سالم البادي، د. مي عبد المطلب محرزي",
    presenterEn: "Dr. Mohamed Rabie Fath El-Bab, Dr. Ali Bin Salem Al-Badi, Dr. May Abdel-Motaleb Maharzi",
    titleAr: "حلقة نقاشية بعنوان: أخلاقيات ومعايير البحث العلمي",
    titleEn: "Discussion Session: Ethics and Standards of Scientific Research",
    date: "2023-12-01",
    isActive: true,
    order: 56,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د.علي بن سالم البادي، د.أيمن عبدالله فكري",
    presenterEn: "Dr. Ali Bin Salem Al-Badi, Dr. Ayman Abdullah Fekry",
    titleAr: "حلقة نقاشية بعنوان: المسؤولية القانونية لاستخدام وسائل تقنية المعلومات",
    titleEn: "Discussion Session: Legal Responsibility for Using Information Technology",
    date: "2023-12-01",
    isActive: true,
    order: 57,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د. أيمن عبدالله فكري",
    presenterEn: "Dr. Ayman Abdullah Fekry",
    titleAr: "حلقة نقاشية بعنوان: جريمة الاحتيال الإلكتروني",
    titleEn: "Discussion Session: Electronic Fraud Crime",
    date: "2023-12-01",
    isActive: true,
    order: 58,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "أ. د. رمضان ابراهيم علام",
    presenterEn: "Prof. Dr. Ramadan Ibrahim Allam",
    titleAr: "حلقة نقاشية بعنوان: دعوى العضل",
    titleEn: "Discussion Session: Disability Claim",
    date: "2023-12-01",
    isActive: true,
    order: 59,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "الشيخ حمود بن عبدالله بن هلال الحوسني",
    presenterEn: "Sheikh Humood Bin Abdullah Bin Hilal Al-Hosni",
    titleAr: "دور لجان التوفيق والمصالحة",
    titleEn: "Role of Conciliation and Reconciliation Committees",
    date: "2024-05-01",
    isActive: true,
    order: 60,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د. عمار بن سعيد المانعي",
    presenterEn: "Dr. Ammar Bin Saeed Al Manei",
    titleAr: "فضل العشر الأواخر من شهر رمضان المبارك",
    titleEn: "The Virtue of the Last Ten Days of the Blessed Month of Ramadan",
    date: "2024-03-01",
    isActive: true,
    order: 61,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "د. سعيد بن جمعة العلوي",
    presenterEn: "Dr. Saeed Bin Jumaa Al Alawi",
    titleAr: "كيف نستقبل شهر رمضان",
    titleEn: "How to Welcome the Month of Ramadan",
    date: "2024-03-01",
    isActive: true,
    order: 62,
  },
  {
    academicYearAr: "2023 - 2024",
    academicYearEn: "2023 - 2024",
    departmentAr: "برنامج القانون",
    departmentEn: "Law Program",
    presenterAr: "أ. د. ياسين ثروت الشاذلي وآخرون",
    presenterEn: "Prof. Dr. Yassin Tharwat Al Shazly and others",
    titleAr: "ندوة قانونية دولية بعنوان: التحكيم التجاري ودوره في تحقيق التنمية المستدامة في ضوء رؤية عمان 2040",
    titleEn: "International Legal Seminar: Commercial Arbitration and Its Role in Achieving Sustainable Development in Light of Oman Vision 2040",
    date: "2024-04-01",
    isActive: true,
    order: 63,
  },
];
