import { ScholarshipItem, TuitionProgram } from "@/types/Tuition";

export const undergradPrograms: TuitionProgram[] = [
    { programAr: 'برنامج اللغة الانجليزية وآدابها', programEn: 'English Language and Literature', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج الترجمة', programEn: 'Translation', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج المحاسبة', programEn: 'Accounting', admission: '100', creditHour: '66.300' },
    { programAr: 'برنامج تنمية الموارد البشرية', programEn: 'Human Resource Development', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج إدارة الأعمال', programEn: 'Business Administration', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج العلوم المالية والمصرفية', programEn: 'Finance and Banking', admission: '100', creditHour: '66.300' },
    { programAr: 'التسويق', programEn: 'Marketing', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج التجارة الدولية', programEn: 'International Trade', admission: '100', creditHour: '56.100' },
    { programAr: 'برنامج اقتصاد الأعمال', programEn: 'Business Economics', admission: '100', creditHour: '65.000' },
    { programAr: 'برنامج نظم المعلومات', programEn: 'Information Systems', admission: '100', creditHour: '66.300' },
    { programAr: 'برنامج علوم الحاسب', programEn: 'Computer Science', admission: '100', creditHour: '66.300' },
    { programAr: 'برنامج هندسة البرمجيات', programEn: 'Software Engineering', admission: '100', creditHour: '66.300' },
    { programAr: 'الذكاء الاصطناعي', programEn: 'Artificial Intelligence', admission: '100', creditHour: '66.300' },
    { programAr: 'الأمن السيبراني', programEn: 'Cybersecurity', admission: '100', creditHour: '66.300' },
    { programAr: 'القانون', programEn: 'Law', admission: '100', creditHour: '66.300' },
];

export const gradPrograms: TuitionProgram[] = [
    { programAr: 'ماجستير القانون', programEn: "Master's in Law", admission: '150', creditHour: '130.000' },
    { programAr: 'ماجستير إدارة الأعمال MBA', programEn: 'Master of Business Administration (MBA)', admission: '150', creditHour: '130.000' },
    { programAr: 'الدكتوراة في القانون', programEn: 'PhD in Law', admission: '150', creditHour: '150.000' },
];

export const scholarships: ScholarshipItem[] = [
    { id: 1, titleAr: 'الطلبة المتفوقين في شهادة الدبلوم العام', titleEn: 'High-achieving students in the General Diploma', percentage: '10%', color: 'blue' },
    { id: 2, titleAr: 'الطلبة المتفوقين دراسياً في البرامج الأكاديمية بالكلية', titleEn: 'Academically outstanding students in college programs', percentage: '10%', color: 'blue' },
    { id: 3, titleAr: 'موظفي المجلس الأعلى للقضاء - لدرجة الدكتوراه', titleEn: 'Supreme Judicial Council employees (PhD)', percentage: '10%', color: 'blue' },
    { id: 4, titleAr: 'الطلبة المسددين لكافة الرسوم الدراسية مسبقاً', titleEn: 'Students who pay all tuition fees in advance', percentage: '10%', color: 'blue' },
    { id: 5, titleAr: 'شرطة عمان السلطانية وذويهم - لدرجة الدكتوراه', titleEn: 'Royal Oman Police and their dependents (PhD)', percentage: '10%', color: 'blue' },
    { id: 6, titleAr: 'حاملي بطاقة "إسعاد" للطلبة الجدد - للدراسات العليا', titleEn: 'Holders of "Es’aad" card (new students - postgraduate)', percentage: '10%', color: 'blue' },
    { id: 7, titleAr: 'حاملي بطاقة "فزعة" للطلبة الجدد - للدراسات العليا', titleEn: 'Holders of "Fazaa" card (new students - postgraduate)', percentage: '10%', color: 'blue' },
    { id: 8, titleAr: 'حاملي بطاقة "تستاهل" للطلبة الجدد - للدراسات العليا', titleEn: 'Holders of "Tastahil" card (new students - postgraduate)', percentage: '10%', color: 'blue' },
    { id: 9, titleAr: 'أبناء موظفي القطاع الخاص والمتقاعدين منهم وأقاربهم من الدرجة الأولى', titleEn: 'Children of private sector employees/retirees and their first-degree relatives', percentage: '15%', color: 'green' },
    { id: 10, titleAr: 'طلبة الضمان الاجتماعي', titleEn: 'Social security students', percentage: '20%', color: 'orange' },
    { id: 11, titleAr: 'الطلبة الدوليين', titleEn: 'International students', percentage: '20%', color: 'orange' },
    { id: 12, titleAr: 'طلبة البعثات الداخلية والمنتهية بعثاتهم والراغبين في استكمال دراستهم لدرجة البكالوريوس', titleEn: 'Internal scholarship students whose scholarships ended and who wish to continue to the bachelor’s degree', percentage: '20%', color: 'orange' },
    { id: 13, titleAr: 'خريجي الدبلوم الراغبين في استكمال دراستهم لدرجة البكالوريوس', titleEn: 'Diploma graduates wishing to continue to the bachelor’s degree', percentage: '20%', color: 'orange' },
    { id: 14, titleAr: 'موظفي المجلس الأعلى للقضاء - لدرجة الماجستير', titleEn: 'Supreme Judicial Council employees (Master’s)', percentage: '20%', color: 'orange' },
    { id: 15, titleAr: 'شرطة عمان السلطانية وذويهم - لدرجة الماجستير', titleEn: 'Royal Oman Police and their dependents (Master’s)', percentage: '20%', color: 'orange' },
    { id: 16, titleAr: 'وزارة الدفاع وذويهم', titleEn: 'Ministry of Defence employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 17, titleAr: 'ديوان البلاط السلطاني وذويهم', titleEn: 'Royal Court Affairs staff and their dependents', percentage: '20%', color: 'orange' },
    { id: 18, titleAr: 'وزارة الصحة وذويهم', titleEn: 'Ministry of Health employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 19, titleAr: 'وزارة التربية والتعليم وذويهم', titleEn: 'Ministry of Education employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 20, titleAr: 'موظفي غرفة تجارة وصناعة عمان وذويهم', titleEn: 'Oman Chamber of Commerce & Industry employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 21, titleAr: 'موظفي شركة مزون للألبان وعائلاتهم', titleEn: 'Mazoon Dairy Company employees and their families', percentage: '20%', color: 'orange' },
    { id: 22, titleAr: 'المؤسسة العامة للمناطق الصناعية (مدائن) وذويهم', titleEn: 'Public Establishment for Industrial Estates (Madayn) employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 23, titleAr: 'أبناء محافظة مسندم', titleEn: 'Students from Musandam Governorate', percentage: '20%', color: 'orange' },
    { id: 24, titleAr: 'المحامين المسجلين - لدرجة الماجستير', titleEn: 'Registered lawyers (Master’s)', percentage: '20%', color: 'orange' },
    { id: 25, titleAr: 'وزارة الأوقاف والشؤون الدينية وذويهم', titleEn: 'Ministry of Endowments and Religious Affairs employees and their dependents', percentage: '20%', color: 'orange' },
    { id: 26, titleAr: 'حاملي بطاقة "إسعاد" للطلبة الجدد - لدرجة البكالوريوس', titleEn: 'Holders of "Es’aad" card (new students - bachelor’s)', percentage: '20%', color: 'orange' },
    { id: 27, titleAr: 'حاملي بطاقة "فزعة" للطلبة الجدد - لدرجة البكالوريوس', titleEn: 'Holders of "Fazaa" card (new students - bachelor’s)', percentage: '20%', color: 'orange' },
    { id: 28, titleAr: 'حاملي بطاقة "تستاهل" للطلبة الجدد - لدرجة البكالوريوس', titleEn: 'Holders of "Tastahil" card (new students - bachelor’s)', percentage: '20%', color: 'orange' },
    { id: 29, titleAr: 'شرطة عمان السلطانية وذويهم - لدرجة البكالوريوس', titleEn: 'Royal Oman Police and their dependents (Bachelor’s)', percentage: '25%', color: 'purple' },
    { id: 30, titleAr: 'موظفي المجلس الأعلى للقضاء - لدرجة البكالوريوس', titleEn: 'Supreme Judicial Council employees (Bachelor’s)', percentage: '30%', color: 'red' },
    { id: 31, titleAr: 'الأشخاص ذوي الاحتياجات الخاصة وأبنائهم', titleEn: 'People with special needs and their children', percentage: '30%', color: 'red' },
    { id: 32, titleAr: 'موظفي كلية البريمي الجامعية وأبنائهم وزوجاتهم', titleEn: 'Al Buraimi University College employees, their children, and spouses', percentage: '30%', color: 'red' },
];
