import { Schema, model, models } from "mongoose";

const FoundationCourseSchema = new Schema(
  {
    code: { type: String, required: true, trim: true },
    titleAr: { type: String, required: true, trim: true },
    titleEn: { type: String, required: true, trim: true },
    credits: { type: Number, required: true, min: 0, default: 0 },
  },
  { _id: false },
);

const FoundationProgramSchema = new Schema(
  {
    level1Details: { type: Schema.Types.Mixed, required: true, default: {} },
    level2Details: { type: Schema.Types.Mixed, required: true, default: {} },
    completionExamDetails: { type: Schema.Types.Mixed, required: true, default: {} },
    level1Courses: { type: [FoundationCourseSchema], required: true, default: [] },
    level2Courses: { type: [FoundationCourseSchema], required: true, default: [] },
    heroTitleAr: { type: String, required: true, trim: true },
    heroTitleEn: { type: String, required: true, trim: true },
    heroSubtitleAr: { type: String, required: true, trim: true },
    heroSubtitleEn: { type: String, required: true, trim: true },
    overviewTitleAr: { type: String, required: true, trim: true },
    overviewTitleEn: { type: String, required: true, trim: true },
    overviewText1Ar: { type: String, required: true, trim: true },
    overviewText1En: { type: String, required: true, trim: true },
    overviewText2Ar: { type: String, required: true, trim: true },
    overviewText2En: { type: String, required: true, trim: true },
    admissionTitleAr: { type: String, required: true, trim: true },
    admissionTitleEn: { type: String, required: true, trim: true },
    admissionTextAr: { type: String, required: true, trim: true },
    admissionTextEn: { type: String, required: true, trim: true },
    studyTitleAr: { type: String, required: true, trim: true, default: "" },
    studyTitleEn: { type: String, required: true, trim: true, default: "" },
    studyNoteAr: { type: String, required: true, trim: true, default: "" },
    studyNoteEn: { type: String, required: true, trim: true, default: "" },
    visionSectionTitleAr: { type: String, required: true, trim: true },
    visionSectionTitleEn: { type: String, required: true, trim: true },
    visionTitleAr: { type: String, required: true, trim: true },
    visionTitleEn: { type: String, required: true, trim: true },
    visionTextAr: { type: String, required: true, trim: true },
    visionTextEn: { type: String, required: true, trim: true },
    missionTitleAr: { type: String, required: true, trim: true },
    missionTitleEn: { type: String, required: true, trim: true },
    missionTextAr: { type: String, required: true, trim: true },
    missionTextEn: { type: String, required: true, trim: true },
    completionTitleAr: { type: String, required: true, trim: true, default: "" },
    completionTitleEn: { type: String, required: true, trim: true, default: "" },
    completionDescriptionAr: { type: String, required: true, trim: true, default: "" },
    completionDescriptionEn: { type: String, required: true, trim: true, default: "" },
    completionRequirementsTitleAr: { type: String, required: true, trim: true, default: "" },
    completionRequirementsTitleEn: { type: String, required: true, trim: true, default: "" },
    completionRequirementsAr: { type: [String], required: true, default: [] },
    completionRequirementsEn: { type: [String], required: true, default: [] },
    completionScheduleTitleAr: { type: String, required: true, trim: true, default: "" },
    completionScheduleTitleEn: { type: String, required: true, trim: true, default: "" },
    completionScheduleTextAr: { type: String, required: true, trim: true, default: "" },
    completionScheduleTextEn: { type: String, required: true, trim: true, default: "" },
    completionButtonLabelAr: { type: String, required: true, trim: true, default: "" },
    completionButtonLabelEn: { type: String, required: true, trim: true, default: "" },
    mathExamTitleAr: { type: String, required: true, trim: true, default: "" },
    mathExamTitleEn: { type: String, required: true, trim: true, default: "" },
    mathExamDescriptionAr: { type: String, required: true, trim: true, default: "" },
    mathExamDescriptionEn: { type: String, required: true, trim: true, default: "" },
    mathExamDurationAr: { type: String, required: true, trim: true, default: "" },
    mathExamDurationEn: { type: String, required: true, trim: true, default: "" },
    mathExamDurationValueAr: { type: String, required: true, trim: true, default: "" },
    mathExamDurationValueEn: { type: String, required: true, trim: true, default: "" },
    mathExamPassMarkAr: { type: String, required: true, trim: true, default: "" },
    mathExamPassMarkEn: { type: String, required: true, trim: true, default: "" },
    mathExamPassMarkValueAr: { type: String, required: true, trim: true, default: "" },
    mathExamPassMarkValueEn: { type: String, required: true, trim: true, default: "" },
    mathExamRetakeAr: { type: String, required: true, trim: true, default: "" },
    mathExamRetakeEn: { type: String, required: true, trim: true, default: "" },
    mathExamRetakeValueAr: { type: String, required: true, trim: true, default: "" },
    mathExamRetakeValueEn: { type: String, required: true, trim: true, default: "" },
    mathExamConditionsTitleAr: { type: String, required: true, trim: true, default: "" },
    mathExamConditionsTitleEn: { type: String, required: true, trim: true, default: "" },
    mathExamConditionsAr: { type: [String], required: true, default: [] },
    mathExamConditionsEn: { type: [String], required: true, default: [] },
    mathExamButtonLabelAr: { type: String, required: true, trim: true, default: "" },
    mathExamButtonLabelEn: { type: String, required: true, trim: true, default: "" },
    // Oxford Test Section
    oxfordTitleAr: { type: String, required: true, trim: true, default: "اختبار تحديد المستوى من أكسفورد" },
    oxfordTitleEn: { type: String, required: true, trim: true, default: "Oxford Placement Test" },
    oxfordDescriptionAr: { type: String, required: true, trim: true, default: "تستخدم الكلية اختبار أكسفورد المعتمد دولياً لتحديد مستوى الطلاب في اللغة الإنجليزية عند القبول." },
    oxfordDescriptionEn: { type: String, required: true, trim: true, default: "The college uses the internationally recognized Oxford test to determine students' English level upon admission." },
    oxfordCard1TitleAr: { type: String, required: true, trim: true, default: "100% عبر الإنترنت" },
    oxfordCard1TitleEn: { type: String, required: true, trim: true, default: "100% Online" },
    oxfordCard1DescAr: { type: String, required: true, trim: true, default: "على أي جهاز ومن أي مكان" },
    oxfordCard1DescEn: { type: String, required: true, trim: true, default: "On any device from anywhere" },
    oxfordCard2TitleAr: { type: String, required: true, trim: true, default: "نتائج فورية" },
    oxfordCard2TitleEn: { type: String, required: true, trim: true, default: "Instant Results" },
    oxfordCard2DescAr: { type: String, required: true, trim: true, default: "التصحيح التلقائي الفوري" },
    oxfordCard2DescEn: { type: String, required: true, trim: true, default: "Automatic instant scoring" },
    oxfordCard3TitleAr: { type: String, required: true, trim: true, default: "مستويات CEFR" },
    oxfordCard3TitleEn: { type: String, required: true, trim: true, default: "CEFR Levels" },
    oxfordCard3DescAr: { type: String, required: true, trim: true, default: "من Pre-A1 إلى C2" },
    oxfordCard3DescEn: { type: String, required: true, trim: true, default: "From Pre-A1 to C2" },
    oxfordFeaturesTitleAr: { type: String, required: true, trim: true, default: "مميزات الاختبار:" },
    oxfordFeaturesTitleEn: { type: String, required: true, trim: true, default: "Test Features:" },
    oxfordFeature1Ar: { type: String, required: true, trim: true, default: "تقنية التكيف الحاسوبي للدقة العالية" },
    oxfordFeature1En: { type: String, required: true, trim: true, default: "Computer-adaptive technology for high accuracy" },
    oxfordFeature2Ar: { type: String, required: true, trim: true, default: "تقارير شاملة ومفصلة" },
    oxfordFeature2En: { type: String, required: true, trim: true, default: "Comprehensive detailed reports" },
    oxfordFeature3Ar: { type: String, required: true, trim: true, default: "ساعد ملايين الطلاب حول العالم" },
    oxfordFeature3En: { type: String, required: true, trim: true, default: "Helped millions of students worldwide" },
    oxfordFeature4Ar: { type: String, required: true, trim: true, default: "معايير دولية معترف بها" },
    oxfordFeature4En: { type: String, required: true, trim: true, default: "Internationally recognized standards" },
    oxfordButtonLabelAr: { type: String, required: true, trim: true, default: "اعرف المزيد عن الاختبار" },
    oxfordButtonLabelEn: { type: String, required: true, trim: true, default: "Learn More About the Test" },
    // Practice Test Section
    practiceTestTitleAr: { type: String, required: true, trim: true, default: "امتحان تحديد المستوى - تدريبي" },
    practiceTestTitleEn: { type: String, required: true, trim: true, default: "Practice Placement Test" },
    practiceTestDescriptionAr: { type: String, required: true, trim: true, default: "توفر الكلية مجموعة من الامتحانات التدريبية المجانية لمساعدة الطلاب على الاستعداد بشكل أفضل لامتحانات تحديد المستوى الرسمية في الرياضيات والحاسب الآلي." },
    practiceTestDescriptionEn: { type: String, required: true, trim: true, default: "The college provides a set of free practice exams to help students better prepare for official placement exams in Mathematics and Computer Science." },
    practiceTestCard1TitleAr: { type: String, required: true, trim: true, default: "امتحانات الرياضيات" },
    practiceTestCard1TitleEn: { type: String, required: true, trim: true, default: "Mathematics Exams" },
    practiceTestCard1DescAr: { type: String, required: true, trim: true, default: "5 امتحانات تدريبية" },
    practiceTestCard1DescEn: { type: String, required: true, trim: true, default: "5 practice exams" },
    practiceTestCard2TitleAr: { type: String, required: true, trim: true, default: "امتحانات الحاسوب" },
    practiceTestCard2TitleEn: { type: String, required: true, trim: true, default: "Computer Exams" },
    practiceTestCard2DescAr: { type: String, required: true, trim: true, default: "2 امتحانات تدريبية" },
    practiceTestCard2DescEn: { type: String, required: true, trim: true, default: "2 practice exams" },
    practiceTestCard3TitleAr: { type: String, required: true, trim: true, default: "محوسب بالكامل" },
    practiceTestCard3TitleEn: { type: String, required: true, trim: true, default: "Fully Computerized" },
    practiceTestCard3DescAr: { type: String, required: true, trim: true, default: "50 دقيقة لكل امتحان" },
    practiceTestCard3DescEn: { type: String, required: true, trim: true, default: "50 minutes per exam" },
    practiceTestFeaturesTitleAr: { type: String, required: true, trim: true, default: "مميزات الامتحانات التدريبية:" },
    practiceTestFeaturesTitleEn: { type: String, required: true, trim: true, default: "Practice Exam Features:" },
    practiceTestFeature1Ar: { type: String, required: true, trim: true, default: "نماذج مطابقة للامتحانات الرسمية" },
    practiceTestFeature1En: { type: String, required: true, trim: true, default: "Models matching official exams" },
    practiceTestFeature2Ar: { type: String, required: true, trim: true, default: "نتائج فورية وتقارير تفصيلية" },
    practiceTestFeature2En: { type: String, required: true, trim: true, default: "Instant results and detailed reports" },
    practiceTestFeature3Ar: { type: String, required: true, trim: true, default: "متاحة مجاناً لجميع الطلاب" },
    practiceTestFeature3En: { type: String, required: true, trim: true, default: "Available free for all students" },
    practiceTestFeature4Ar: { type: String, required: true, trim: true, default: "إمكانية إعادة الامتحان عدة مرات" },
    practiceTestFeature4En: { type: String, required: true, trim: true, default: "Ability to retake the exam multiple times" },
    practiceTestButtonLabelAr: { type: String, required: true, trim: true, default: "عرض جميع الامتحانات التدريبية" },
    practiceTestButtonLabelEn: { type: String, required: true, trim: true, default: "View All Practice Exams" },
    // Faculty Section
    facultyTitleAr: { type: String, required: true, trim: true, default: "أعضاء الهيئة التدريسية" },
    facultyTitleEn: { type: String, required: true, trim: true, default: "Faculty Members" },
    facultyDescriptionAr: { type: String, required: true, trim: true, default: "يتميز البرنامج التأسيسي بهيئة تدريسية مؤهلة وذات خبرة عالية في مجالات التدريس والتوجيه الأكاديمي. يضم فريقنا 12 عضواً من الأساتذة والمحاضرين المتخصصين." },
    facultyDescriptionEn: { type: String, required: true, trim: true, default: "The Foundation Program is distinguished by a qualified teaching staff with extensive experience in teaching and academic guidance. Our team includes 12 specialized professors and lecturers." },
    facultyCard1TitleAr: { type: String, required: true, trim: true, default: "إجمالي الأعضاء" },
    facultyCard1TitleEn: { type: String, required: true, trim: true, default: "Total Members" },
    facultyCard1ValueAr: { type: String, required: true, trim: true, default: "12" },
    facultyCard1ValueEn: { type: String, required: true, trim: true, default: "12" },
    facultyCard2TitleAr: { type: String, required: true, trim: true, default: "قسم اللغة الإنجليزية" },
    facultyCard2TitleEn: { type: String, required: true, trim: true, default: "English Department" },
    facultyCard2DescAr: { type: String, required: true, trim: true, default: "أساتذة متخصصون في تعليم اللغة الإنجليزية" },
    facultyCard2DescEn: { type: String, required: true, trim: true, default: "Specialized professors in English language teaching" },
    facultyCard3TitleAr: { type: String, required: true, trim: true, default: "قسم تكنولوجيا المعلومات" },
    facultyCard3TitleEn: { type: String, required: true, trim: true, default: "IT Department" },
    facultyCard3DescAr: { type: String, required: true, trim: true, default: "متخصصون في تقنية المعلومات" },
    facultyCard3DescEn: { type: String, required: true, trim: true, default: "Information technology specialists" },
    facultyCard1Icon: { type: String, required: true, trim: true, default: "users" },
    facultyCard2Icon: { type: String, required: true, trim: true, default: "book-open" },
    facultyCard3Icon: { type: String, required: true, trim: true, default: "monitor" },
    facultyButtonLabelAr: { type: String, required: true, trim: true, default: "تعرف على أعضاء هيئة التدريس" },
    facultyButtonLabelEn: { type: String, required: true, trim: true, default: "Meet the Faculty Members" },
    // CTA Section
    ctaTitleAr: { type: String, required: true, trim: true, default: "هل أنت مستعد للبدء في رحلتك الأكاديمية؟" },
    ctaTitleEn: { type: String, required: true, trim: true, default: "Ready to Start Your Academic Journey?" },
    ctaDescriptionAr: { type: String, required: true, trim: true, default: "انضم إلى البرنامج التأسيسي العام في كلية البريمي الجامعية وابدأ طريقك نحو النجاح الأكاديمي" },
    ctaDescriptionEn: { type: String, required: true, trim: true, default: "Join the General Foundation Program at Al Buraimi University College and start your path to academic success" },
    ctaButton1LabelAr: { type: String, required: true, trim: true, default: "تقدم الآن" },
    ctaButton1LabelEn: { type: String, required: true, trim: true, default: "Apply Now" },
    ctaButton2LabelAr: { type: String, required: true, trim: true, default: "تواصل معنا" },
    ctaButton2LabelEn: { type: String, required: true, trim: true, default: "Contact Us" },
    facultyPageDetails: { type: Schema.Types.Mixed, required: true, default: {} },
  },
  { timestamps: true },
);

if (process.env.NODE_ENV !== "production" && models.FoundationProgram) {
  delete models.FoundationProgram;
}

export const FoundationProgramModel = model(
  "FoundationProgram",
  FoundationProgramSchema,
);
