import { Schema, model } from "mongoose";
import type { MathCompletionExamData } from "@/staticData/math-completion-exam";

const MathCompletionExamSchema = new Schema<MathCompletionExamData>(
  {
    heroTitleAr: { type: String, required: true, default: "امتحان إنهاء متطلب الرياضيات" },
    heroTitleEn: { type: String, required: true, default: "Mathematics Exit Exam" },
    heroSubtitleAr: { type: String, required: true, default: "امتحان الخروج من البرنامج التأسيسي للرياضيات" },
    heroSubtitleEn: { type: String, required: true, default: "Foundation Program Mathematics Exit Exam" },
    aboutTitleAr: { type: String, required: true, default: "نبذة عن الامتحان" },
    aboutTitleEn: { type: String, required: true, default: "About the Exam" },
    aboutDescriptionAr: { type: String, required: true },
    aboutDescriptionEn: { type: String, required: true },
    aboutGoalTitleAr: { type: String, required: true, default: "الهدف من الامتحان" },
    aboutGoalTitleEn: { type: String, required: true, default: "Exam Objective" },
    aboutGoalTextAr: { type: String, required: true },
    aboutGoalTextEn: { type: String, required: true },
    durationLabelAr: { type: String, required: true, default: "مدة الامتحان" },
    durationLabelEn: { type: String, required: true, default: "Exam Duration" },
    durationValueAr: { type: String, required: true, default: "50 دقيقة" },
    durationValueEn: { type: String, required: true, default: "50 Minutes" },
    durationNoteAr: { type: String, required: true },
    durationNoteEn: { type: String, required: true },
    passMarkLabelAr: { type: String, required: true, default: "علامة النجاح" },
    passMarkLabelEn: { type: String, required: true, default: "Passing Score" },
    passMarkValueAr: { type: String, required: true, default: "50/100" },
    passMarkValueEn: { type: String, required: true, default: "50/100" },
    passMarkNoteAr: { type: String, required: true },
    passMarkNoteEn: { type: String, required: true },
    retakeLabelAr: { type: String, required: true, default: "فرص الإعادة" },
    retakeLabelEn: { type: String, required: true, default: "Retake Opportunities" },
    retakeValueAr: { type: String, required: true, default: "فرصة ثانية" },
    retakeValueEn: { type: String, required: true, default: "Second Chance" },
    retakeNoteAr: { type: String, required: true },
    retakeNoteEn: { type: String, required: true },
    eligibilityTitleAr: { type: String, required: true, default: "شروط الأهلية للامتحان" },
    eligibilityTitleEn: { type: String, required: true, default: "Exam Eligibility Conditions" },
    eligibilityAppliedMathTitleAr: { type: String, required: true, default: "اجتياز مقرر الرياضيات التطبيقية" },
    eligibilityAppliedMathTitleEn: { type: String, required: true, default: "Pass Applied Mathematics Course" },
    eligibilityAppliedMathDescAr: { type: String, required: true },
    eligibilityAppliedMathDescEn: { type: String, required: true },
    eligibilityPureMathTitleAr: { type: String, required: true, default: "اجتياز مقرر الرياضيات البحتة" },
    eligibilityPureMathTitleEn: { type: String, required: true, default: "Pass Pure Mathematics Course" },
    eligibilityPureMathDescAr: { type: String, required: true },
    eligibilityPureMathDescEn: { type: String, required: true },
    eligibilityNoteTitleAr: { type: String, required: true, default: "ملاحظة مهمة" },
    eligibilityNoteTitleEn: { type: String, required: true, default: "Important Note" },
    eligibilityNoteTextAr: { type: String, required: true },
    eligibilityNoteTextEn: { type: String, required: true },
    // Exam Structure Section
    structureTitleAr: { type: String, required: true, default: "هيكل الامتحان" },
    structureTitleEn: { type: String, required: true, default: "Exam Structure" },
    structureHeaderSectionAr: { type: String, required: true, default: "القسم" },
    structureHeaderSectionEn: { type: String, required: true, default: "Section" },
    structureHeaderTypeAr: { type: String, required: true, default: "نوع الأسئلة" },
    structureHeaderTypeEn: { type: String, required: true, default: "Question Type" },
    structureHeaderCountAr: { type: String, required: true, default: "عدد الأسئلة" },
    structureHeaderCountEn: { type: String, required: true, default: "Number of Questions" },
    structureHeaderMarksAr: { type: String, required: true, default: "الدرجات" },
    structureHeaderMarksEn: { type: String, required: true, default: "Marks" },
    structureHeaderPercentAr: { type: String, required: true, default: "النسبة" },
    structureHeaderPercentEn: { type: String, required: true, default: "Percentage" },
    // Row 1
    structureRow1SectionAr: { type: String, required: true, default: "الجزء الأول" },
    structureRow1SectionEn: { type: String, required: true, default: "Part One" },
    structureRow1TypeAr: { type: String, required: true, default: "أسئلة اختيار من متعدد" },
    structureRow1TypeEn: { type: String, required: true, default: "Multiple Choice Questions" },
    structureRow1CountAr: { type: String, required: true, default: "20 سؤال" },
    structureRow1CountEn: { type: String, required: true, default: "20 Questions" },
    structureRow1MarksAr: { type: String, required: true, default: "40 درجة" },
    structureRow1MarksEn: { type: String, required: true, default: "40 Marks" },
    structureRow1PercentAr: { type: String, required: true, default: "40%" },
    structureRow1PercentEn: { type: String, required: true, default: "40%" },
    // Row 2
    structureRow2SectionAr: { type: String, required: true, default: "الجزء الثاني" },
    structureRow2SectionEn: { type: String, required: true, default: "Part Two" },
    structureRow2TypeAr: { type: String, required: true, default: "أسئلة مقالية قصيرة" },
    structureRow2TypeEn: { type: String, required: true, default: "Short Essay Questions" },
    structureRow2CountAr: { type: String, required: true, default: "6 أسئلة" },
    structureRow2CountEn: { type: String, required: true, default: "6 Questions" },
    structureRow2MarksAr: { type: String, required: true, default: "30 درجة" },
    structureRow2MarksEn: { type: String, required: true, default: "30 Marks" },
    structureRow2PercentAr: { type: String, required: true, default: "30%" },
    structureRow2PercentEn: { type: String, required: true, default: "30%" },
    // Row 3
    structureRow3SectionAr: { type: String, required: true, default: "الجزء الثالث" },
    structureRow3SectionEn: { type: String, required: true, default: "Part Three" },
    structureRow3TypeAr: { type: String, required: true, default: "مسائل طويلة" },
    structureRow3TypeEn: { type: String, required: true, default: "Long Problems" },
    structureRow3CountAr: { type: String, required: true, default: "3 مسائل" },
    structureRow3CountEn: { type: String, required: true, default: "3 Problems" },
    structureRow3MarksAr: { type: String, required: true, default: "30 درجة" },
    structureRow3MarksEn: { type: String, required: true, default: "30 Marks" },
    structureRow3PercentAr: { type: String, required: true, default: "30%" },
    structureRow3PercentEn: { type: String, required: true, default: "30%" },
    // Total Row
    structureTotalLabelAr: { type: String, required: true, default: "المجموع الكلي" },
    structureTotalLabelEn: { type: String, required: true, default: "Total" },
    structureTotalMarksAr: { type: String, required: true, default: "100 درجة" },
    structureTotalMarksEn: { type: String, required: true, default: "100 Marks" },
    structureTotalPercentAr: { type: String, required: true, default: "100%" },
    structureTotalPercentEn: { type: String, required: true, default: "100%" },
    // Note
    structureNoteLabelAr: { type: String, required: true, default: "ملاحظة" },
    structureNoteLabelEn: { type: String, required: true, default: "Note" },
    structureNoteTextAr: { type: String, required: true, default: "يجب الحصول على 50 درجة على الأقل من 100 درجة لاجتياز الامتحان بنجاح." },
    structureNoteTextEn: { type: String, required: true, default: "You must obtain at least 50 out of 100 marks to pass the exam successfully." },
    // Topics Section
    topicsTitleAr: { type: String, required: true, default: "المواضيع المشمولة في الامتحان" },
    topicsTitleEn: { type: String, required: true, default: "Exam Topics" },
    // Card 1 - Algebra (blue)
    topicsCard1TitleAr: { type: String, required: true, default: "الجبر" },
    topicsCard1TitleEn: { type: String, required: true, default: "Algebra" },
    topicsCard1Item1Ar: { type: String, required: true, default: "المعادلات الخطية والتربيعية" },
    topicsCard1Item1En: { type: String, required: true, default: "Linear and Quadratic Equations" },
    topicsCard1Item2Ar: { type: String, required: true, default: "حل أنظمة المعادلات" },
    topicsCard1Item2En: { type: String, required: true, default: "Solving Systems of Equations" },
    topicsCard1Item3Ar: { type: String, required: true, default: "المتباينات" },
    topicsCard1Item3En: { type: String, required: true, default: "Inequalities" },
    topicsCard1Item4Ar: { type: String, required: true, default: "الأسس والجذور" },
    topicsCard1Item4En: { type: String, required: true, default: "Exponents and Roots" },
    topicsCard1Item5Ar: { type: String, required: true, default: "اللوغاريتمات" },
    topicsCard1Item5En: { type: String, required: true, default: "Logarithms" },
    // Card 2 - Geometry (green)
    topicsCard2TitleAr: { type: String, required: true, default: "الهندسة" },
    topicsCard2TitleEn: { type: String, required: true, default: "Geometry" },
    topicsCard2Item1Ar: { type: String, required: true, default: "خصائص الأشكال الهندسية" },
    topicsCard2Item1En: { type: String, required: true, default: "Properties of Geometric Shapes" },
    topicsCard2Item2Ar: { type: String, required: true, default: "حساب المساحات والمحيطات" },
    topicsCard2Item2En: { type: String, required: true, default: "Calculating Areas and Perimeters" },
    topicsCard2Item3Ar: { type: String, required: true, default: "حساب الحجوم" },
    topicsCard2Item3En: { type: String, required: true, default: "Calculating Volumes" },
    topicsCard2Item4Ar: { type: String, required: true, default: "نظرية فيثاغورس" },
    topicsCard2Item4En: { type: String, required: true, default: "Pythagorean Theorem" },
    topicsCard2Item5Ar: { type: String, required: true, default: "الإحداثيات الديكارتية" },
    topicsCard2Item5En: { type: String, required: true, default: "Cartesian Coordinates" },
    // Card 3 - Statistics (purple)
    topicsCard3TitleAr: { type: String, required: true, default: "الإحصاء والاحتمالات" },
    topicsCard3TitleEn: { type: String, required: true, default: "Statistics and Probability" },
    topicsCard3Item1Ar: { type: String, required: true, default: "الوسط الحسابي والوسيط والمنوال" },
    topicsCard3Item1En: { type: String, required: true, default: "Mean, Median, and Mode" },
    topicsCard3Item2Ar: { type: String, required: true, default: "التباين والانحراف المعياري" },
    topicsCard3Item2En: { type: String, required: true, default: "Variance and Standard Deviation" },
    topicsCard3Item3Ar: { type: String, required: true, default: "الاحتمالات البسيطة" },
    topicsCard3Item3En: { type: String, required: true, default: "Basic Probability" },
    topicsCard3Item4Ar: { type: String, required: true, default: "التوزيعات الإحصائية" },
    topicsCard3Item4En: { type: String, required: true, default: "Statistical Distributions" },
    topicsCard3Item5Ar: { type: String, required: true, default: "تمثيل البيانات بيانياً" },
    topicsCard3Item5En: { type: String, required: true, default: "Graphical Data Representation" },
    // Card 4 - Calculus (amber)
    topicsCard4TitleAr: { type: String, required: true, default: "التفاضل والتكامل (أساسيات)" },
    topicsCard4TitleEn: { type: String, required: true, default: "Calculus (Basics)" },
    topicsCard4Item1Ar: { type: String, required: true, default: "مفهوم المشتقة" },
    topicsCard4Item1En: { type: String, required: true, default: "Concept of Derivative" },
    topicsCard4Item2Ar: { type: String, required: true, default: "قواعد الاشتقاق الأساسية" },
    topicsCard4Item2En: { type: String, required: true, default: "Basic Differentiation Rules" },
    topicsCard4Item3Ar: { type: String, required: true, default: "تطبيقات المشتقات" },
    topicsCard4Item3En: { type: String, required: true, default: "Applications of Derivatives" },
    topicsCard4Item4Ar: { type: String, required: true, default: "مفهوم التكامل" },
    topicsCard4Item4En: { type: String, required: true, default: "Concept of Integration" },
    topicsCard4Item5Ar: { type: String, required: true, default: "التكامل البسيط" },
    topicsCard4Item5En: { type: String, required: true, default: "Basic Integration" },
    // Retake Policy Section
    retakePolicyTitleAr: { type: String, required: true, default: "سياسة إعادة الامتحان" },
    retakePolicyTitleEn: { type: String, required: true, default: "Exam Retake Policy" },
    retakePolicyItem1Ar: { type: String, required: true, default: "يمكن للطلاب الذين رسبوا في المحاولة الأولى الحصول على فرصة أخرى لإعادة الامتحان" },
    retakePolicyItem1En: { type: String, required: true, default: "Students who failed the first attempt can get another opportunity to retake the exam" },
    retakePolicyItem2Ar: { type: String, required: true, default: "يُعقد امتحان الإعادة في الأسبوع الثاني من الفصل الدراسي التالي" },
    retakePolicyItem2En: { type: String, required: true, default: "The retake exam is held in the second week of the following academic semester" },
    retakePolicyItem3Ar: { type: String, required: true, default: "يجب على الطلاب التسجيل لإعادة الامتحان خلال الفترة المحددة" },
    retakePolicyItem3En: { type: String, required: true, default: "Students must register for the retake exam within the specified period" },
    retakePolicyItem4Ar: { type: String, required: true, default: "لا توجد رسوم إضافية لإعادة الامتحان للمرة الأولى" },
    retakePolicyItem4En: { type: String, required: true, default: "There are no additional fees for the first retake of the exam" },
    retakePolicyItem5Ar: { type: String, required: true, default: "يُحسب أفضل درجة حصل عليها الطالب في المحاولتين" },
    retakePolicyItem5En: { type: String, required: true, default: "The best score obtained by the student in both attempts is counted" },
    retakePolicyNoteTitleAr: { type: String, required: true, default: "تنبيه" },
    retakePolicyNoteTitleEn: { type: String, required: true, default: "Note" },
    retakePolicyNoteTextAr: { type: String, required: true, default: "يُنصح الطلاب بالتحضير جيداً قبل إعادة الامتحان واستغلال الوقت بين المحاولتين للمراجعة المكثفة والتدرب على حل المسائل." },
    retakePolicyNoteTextEn: { type: String, required: true, default: "Students are advised to prepare well before retaking the exam and utilize the time between attempts for intensive review and practice solving problems." },
    // Benefits Section
    benefitsTitleAr: { type: String, required: true, default: "فوائد اجتياز الامتحان" },
    benefitsTitleEn: { type: String, required: true, default: "Benefits of Passing the Exam" },
    benefitsItem1Ar: { type: String, required: true, default: "إكمال متطلبات البرنامج التأسيسي في الرياضيات" },
    benefitsItem1En: { type: String, required: true, default: "Completion of Foundation Program Mathematics requirements" },
    benefitsItem2Ar: { type: String, required: true, default: "الأهلية للانتقال إلى البرنامج الأكاديمي" },
    benefitsItem2En: { type: String, required: true, default: "Eligibility to transition to the academic program" },
    benefitsItem3Ar: { type: String, required: true, default: "عدم الحاجة لدراسة مقررات رياضيات إضافية" },
    benefitsItem3En: { type: String, required: true, default: "No need to study additional mathematics courses" },
    benefitsItem4Ar: { type: String, required: true, default: "تحسين المعدل التراكمي في البرنامج التأسيسي" },
    benefitsItem4En: { type: String, required: true, default: "Improvement of GPA in the Foundation Program" },
    benefitsItem5Ar: { type: String, required: true, default: "إظهار الكفاءة في المهارات الرياضية الأساسية" },
    benefitsItem5En: { type: String, required: true, default: "Demonstrating competency in basic mathematical skills" },
    benefitsFooterTitleAr: { type: String, required: true, default: "إنجاز أكاديمي مهم" },
    benefitsFooterTitleEn: { type: String, required: true, default: "Important Academic Achievement" },
    benefitsFooterTextAr: { type: String, required: true, default: "اجتياز امتحان إنهاء متطلب الرياضيات يعتبر إنجازاً أكاديمياً مهماً يعكس تمكن الطالب من المهارات الرياضية الأساسية اللازمة للنجاح في الدراسات الجامعية." },
    benefitsFooterTextEn: { type: String, required: true, default: "Passing the Mathematics Exit Exam is considered an important academic achievement that reflects the student's mastery of basic mathematical skills necessary for success in university studies." },
    // Tips Section
    tipsTitleAr: { type: String, required: true, default: "نصائح للتحضير للامتحان" },
    tipsTitleEn: { type: String, required: true, default: "Exam Preparation Tips" },
    // Tip 1
    tipsItem1TitleAr: { type: String, required: true, default: "مراجعة المفاهيم الأساسية" },
    tipsItem1TitleEn: { type: String, required: true, default: "Review Basic Concepts" },
    tipsItem1DescAr: { type: String, required: true, default: "راجع جميع المفاهيم والقواعد الأساسية التي تم تدريسها في المقرر" },
    tipsItem1DescEn: { type: String, required: true, default: "Review all basic concepts and rules taught in the course" },
    // Tip 2
    tipsItem2TitleAr: { type: String, required: true, default: "حل المسائل التدريبية" },
    tipsItem2TitleEn: { type: String, required: true, default: "Solve Practice Problems" },
    tipsItem2DescAr: { type: String, required: true, default: "تدرب على حل أكبر عدد ممكن من المسائل المشابهة للامتحان" },
    tipsItem2DescEn: { type: String, required: true, default: "Practice solving as many similar problems as possible" },
    // Tip 3
    tipsItem3TitleAr: { type: String, required: true, default: "إدارة الوقت" },
    tipsItem3TitleEn: { type: String, required: true, default: "Time Management" },
    tipsItem3DescAr: { type: String, required: true, default: "تدرب على حل الامتحانات في الوقت المحدد (50 دقيقة)" },
    tipsItem3DescEn: { type: String, required: true, default: "Practice solving exams within the time limit (50 minutes)" },
    // Tip 4
    tipsItem4TitleAr: { type: String, required: true, default: "طلب المساعدة" },
    tipsItem4TitleEn: { type: String, required: true, default: "Ask for Help" },
    tipsItem4DescAr: { type: String, required: true, default: "لا تتردد في طلب المساعدة من المدرسين في المواضيع الصعبة" },
    tipsItem4DescEn: { type: String, required: true, default: "Don't hesitate to ask teachers for help with difficult topics" },
    // Tips Footer
    tipsFooterTitleAr: { type: String, required: true, default: "مصادر إضافية للمراجعة:" },
    tipsFooterTitleEn: { type: String, required: true, default: "Additional Review Resources:" },
    tipsResource1Ar: { type: String, required: true, default: "نماذج امتحانات سابقة" },
    tipsResource1En: { type: String, required: true, default: "Previous Exam Samples" },
    tipsResource2Ar: { type: String, required: true, default: "ملخصات المقرر" },
    tipsResource2En: { type: String, required: true, default: "Course Summaries" },
    tipsResource3Ar: { type: String, required: true, default: "قوائم المصطلحات" },
    tipsResource3En: { type: String, required: true, default: "Terminology Lists" },
  },
  { timestamps: true }
);

export const MathCompletionExamModel = model("MathCompletionExam", MathCompletionExamSchema);
